/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js';
export { Prisma };
export * as $Enums from './enums.js';
export * from './enums.js';
/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
/**
 * Model Exercise
 *
 */
export type Exercise = Prisma.ExerciseModel;
/**
 * Model WorkoutTemplate
 *
 */
export type WorkoutTemplate = Prisma.WorkoutTemplateModel;
/**
 * Model WorkoutTemplateExercise
 *
 */
export type WorkoutTemplateExercise = Prisma.WorkoutTemplateExerciseModel;
/**
 * Model WorkoutSession
 *
 */
export type WorkoutSession = Prisma.WorkoutSessionModel;
/**
 * Model WorkoutSessionExercise
 *
 */
export type WorkoutSessionExercise = Prisma.WorkoutSessionExerciseModel;
/**
 * Model Set
 *
 */
export type Set = Prisma.SetModel;
/**
 * Model Routine
 *
 */
export type Routine = Prisma.RoutineModel;
/**
 * Model RoutineTemplate
 *
 */
export type RoutineTemplate = Prisma.RoutineTemplateModel;
