/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.js';
export type * from './models/Exercise.js';
export type * from './models/WorkoutTemplate.js';
export type * from './models/WorkoutTemplateExercise.js';
export type * from './models/WorkoutSession.js';
export type * from './models/WorkoutSessionExercise.js';
export type * from './models/Set.js';
export type * from './models/Routine.js';
export type * from './models/RoutineTemplate.js';
export type * from './commonInputTypes.js';
