/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `RoutineTemplate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model RoutineTemplate
 *
 */
export type RoutineTemplateModel =
    runtime.Types.Result.DefaultSelection<Prisma.$RoutineTemplatePayload>;

export type AggregateRoutineTemplate = {
    _count: RoutineTemplateCountAggregateOutputType | null;
    _avg: RoutineTemplateAvgAggregateOutputType | null;
    _sum: RoutineTemplateSumAggregateOutputType | null;
    _min: RoutineTemplateMinAggregateOutputType | null;
    _max: RoutineTemplateMaxAggregateOutputType | null;
};

export type RoutineTemplateAvgAggregateOutputType = {
    dayOfWeek: number | null;
};

export type RoutineTemplateSumAggregateOutputType = {
    dayOfWeek: number | null;
};

export type RoutineTemplateMinAggregateOutputType = {
    id: string | null;
    routineId: string | null;
    workoutTemplateId: string | null;
    dayOfWeek: number | null;
};

export type RoutineTemplateMaxAggregateOutputType = {
    id: string | null;
    routineId: string | null;
    workoutTemplateId: string | null;
    dayOfWeek: number | null;
};

export type RoutineTemplateCountAggregateOutputType = {
    id: number;
    routineId: number;
    workoutTemplateId: number;
    dayOfWeek: number;
    _all: number;
};

export type RoutineTemplateAvgAggregateInputType = {
    dayOfWeek?: true;
};

export type RoutineTemplateSumAggregateInputType = {
    dayOfWeek?: true;
};

export type RoutineTemplateMinAggregateInputType = {
    id?: true;
    routineId?: true;
    workoutTemplateId?: true;
    dayOfWeek?: true;
};

export type RoutineTemplateMaxAggregateInputType = {
    id?: true;
    routineId?: true;
    workoutTemplateId?: true;
    dayOfWeek?: true;
};

export type RoutineTemplateCountAggregateInputType = {
    id?: true;
    routineId?: true;
    workoutTemplateId?: true;
    dayOfWeek?: true;
    _all?: true;
};

export type RoutineTemplateAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which RoutineTemplate to aggregate.
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of RoutineTemplates to fetch.
     */
    orderBy?:
        | Prisma.RoutineTemplateOrderByWithRelationInput
        | Prisma.RoutineTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.RoutineTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` RoutineTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` RoutineTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned RoutineTemplates
     **/
    _count?: true | RoutineTemplateCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: RoutineTemplateAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: RoutineTemplateSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: RoutineTemplateMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: RoutineTemplateMaxAggregateInputType;
};

export type GetRoutineTemplateAggregateType<
    T extends RoutineTemplateAggregateArgs,
> = {
    [P in keyof T & keyof AggregateRoutineTemplate]: P extends
        | '_count'
        | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateRoutineTemplate[P]>
        : Prisma.GetScalarType<T[P], AggregateRoutineTemplate[P]>;
};

export type RoutineTemplateGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.RoutineTemplateWhereInput;
    orderBy?:
        | Prisma.RoutineTemplateOrderByWithAggregationInput
        | Prisma.RoutineTemplateOrderByWithAggregationInput[];
    by:
        | Prisma.RoutineTemplateScalarFieldEnum[]
        | Prisma.RoutineTemplateScalarFieldEnum;
    having?: Prisma.RoutineTemplateScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: RoutineTemplateCountAggregateInputType | true;
    _avg?: RoutineTemplateAvgAggregateInputType;
    _sum?: RoutineTemplateSumAggregateInputType;
    _min?: RoutineTemplateMinAggregateInputType;
    _max?: RoutineTemplateMaxAggregateInputType;
};

export type RoutineTemplateGroupByOutputType = {
    id: string;
    routineId: string;
    workoutTemplateId: string;
    dayOfWeek: number | null;
    _count: RoutineTemplateCountAggregateOutputType | null;
    _avg: RoutineTemplateAvgAggregateOutputType | null;
    _sum: RoutineTemplateSumAggregateOutputType | null;
    _min: RoutineTemplateMinAggregateOutputType | null;
    _max: RoutineTemplateMaxAggregateOutputType | null;
};

export type GetRoutineTemplateGroupByPayload<
    T extends RoutineTemplateGroupByArgs,
> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<RoutineTemplateGroupByOutputType, T['by']> & {
            [P in keyof T &
                keyof RoutineTemplateGroupByOutputType]: P extends '_count'
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<
                          T[P],
                          RoutineTemplateGroupByOutputType[P]
                      >
                : Prisma.GetScalarType<
                      T[P],
                      RoutineTemplateGroupByOutputType[P]
                  >;
        }
    >
>;

export type RoutineTemplateWhereInput = {
    AND?: Prisma.RoutineTemplateWhereInput | Prisma.RoutineTemplateWhereInput[];
    OR?: Prisma.RoutineTemplateWhereInput[];
    NOT?: Prisma.RoutineTemplateWhereInput | Prisma.RoutineTemplateWhereInput[];
    id?: Prisma.StringFilter<'RoutineTemplate'> | string;
    routineId?: Prisma.StringFilter<'RoutineTemplate'> | string;
    workoutTemplateId?: Prisma.StringFilter<'RoutineTemplate'> | string;
    dayOfWeek?: Prisma.IntNullableFilter<'RoutineTemplate'> | number | null;
    routine?: Prisma.XOR<
        Prisma.RoutineScalarRelationFilter,
        Prisma.RoutineWhereInput
    >;
    workoutTemplate?: Prisma.XOR<
        Prisma.WorkoutTemplateScalarRelationFilter,
        Prisma.WorkoutTemplateWhereInput
    >;
};

export type RoutineTemplateOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    routineId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    dayOfWeek?: Prisma.SortOrderInput | Prisma.SortOrder;
    routine?: Prisma.RoutineOrderByWithRelationInput;
    workoutTemplate?: Prisma.WorkoutTemplateOrderByWithRelationInput;
};

export type RoutineTemplateWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?:
            | Prisma.RoutineTemplateWhereInput
            | Prisma.RoutineTemplateWhereInput[];
        OR?: Prisma.RoutineTemplateWhereInput[];
        NOT?:
            | Prisma.RoutineTemplateWhereInput
            | Prisma.RoutineTemplateWhereInput[];
        routineId?: Prisma.StringFilter<'RoutineTemplate'> | string;
        workoutTemplateId?: Prisma.StringFilter<'RoutineTemplate'> | string;
        dayOfWeek?: Prisma.IntNullableFilter<'RoutineTemplate'> | number | null;
        routine?: Prisma.XOR<
            Prisma.RoutineScalarRelationFilter,
            Prisma.RoutineWhereInput
        >;
        workoutTemplate?: Prisma.XOR<
            Prisma.WorkoutTemplateScalarRelationFilter,
            Prisma.WorkoutTemplateWhereInput
        >;
    },
    'id'
>;

export type RoutineTemplateOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    routineId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    dayOfWeek?: Prisma.SortOrderInput | Prisma.SortOrder;
    _count?: Prisma.RoutineTemplateCountOrderByAggregateInput;
    _avg?: Prisma.RoutineTemplateAvgOrderByAggregateInput;
    _max?: Prisma.RoutineTemplateMaxOrderByAggregateInput;
    _min?: Prisma.RoutineTemplateMinOrderByAggregateInput;
    _sum?: Prisma.RoutineTemplateSumOrderByAggregateInput;
};

export type RoutineTemplateScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.RoutineTemplateScalarWhereWithAggregatesInput
        | Prisma.RoutineTemplateScalarWhereWithAggregatesInput[];
    OR?: Prisma.RoutineTemplateScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.RoutineTemplateScalarWhereWithAggregatesInput
        | Prisma.RoutineTemplateScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<'RoutineTemplate'> | string;
    routineId?: Prisma.StringWithAggregatesFilter<'RoutineTemplate'> | string;
    workoutTemplateId?:
        | Prisma.StringWithAggregatesFilter<'RoutineTemplate'>
        | string;
    dayOfWeek?:
        | Prisma.IntNullableWithAggregatesFilter<'RoutineTemplate'>
        | number
        | null;
};

export type RoutineTemplateCreateInput = {
    id?: string;
    dayOfWeek?: number | null;
    routine: Prisma.RoutineCreateNestedOneWithoutTemplatesInput;
    workoutTemplate: Prisma.WorkoutTemplateCreateNestedOneWithoutRoutinesInput;
};

export type RoutineTemplateUncheckedCreateInput = {
    id?: string;
    routineId: string;
    workoutTemplateId: string;
    dayOfWeek?: number | null;
};

export type RoutineTemplateUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
    routine?: Prisma.RoutineUpdateOneRequiredWithoutTemplatesNestedInput;
    workoutTemplate?: Prisma.WorkoutTemplateUpdateOneRequiredWithoutRoutinesNestedInput;
};

export type RoutineTemplateUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    routineId?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateCreateManyInput = {
    id?: string;
    routineId: string;
    workoutTemplateId: string;
    dayOfWeek?: number | null;
};

export type RoutineTemplateUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    routineId?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateListRelationFilter = {
    every?: Prisma.RoutineTemplateWhereInput;
    some?: Prisma.RoutineTemplateWhereInput;
    none?: Prisma.RoutineTemplateWhereInput;
};

export type RoutineTemplateOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type RoutineTemplateCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    routineId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    dayOfWeek?: Prisma.SortOrder;
};

export type RoutineTemplateAvgOrderByAggregateInput = {
    dayOfWeek?: Prisma.SortOrder;
};

export type RoutineTemplateMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    routineId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    dayOfWeek?: Prisma.SortOrder;
};

export type RoutineTemplateMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    routineId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    dayOfWeek?: Prisma.SortOrder;
};

export type RoutineTemplateSumOrderByAggregateInput = {
    dayOfWeek?: Prisma.SortOrder;
};

export type RoutineTemplateCreateNestedManyWithoutWorkoutTemplateInput = {
    create?:
        | Prisma.XOR<
              Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput,
              Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput
          >
        | Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput[]
        | Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput[];
    connectOrCreate?:
        | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput
        | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput[];
    createMany?: Prisma.RoutineTemplateCreateManyWorkoutTemplateInputEnvelope;
    connect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
};

export type RoutineTemplateUncheckedCreateNestedManyWithoutWorkoutTemplateInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput,
                  Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput
              >
            | Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput[]
            | Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput[];
        connectOrCreate?:
            | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput
            | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput[];
        createMany?: Prisma.RoutineTemplateCreateManyWorkoutTemplateInputEnvelope;
        connect?:
            | Prisma.RoutineTemplateWhereUniqueInput
            | Prisma.RoutineTemplateWhereUniqueInput[];
    };

export type RoutineTemplateUpdateManyWithoutWorkoutTemplateNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput,
              Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput
          >
        | Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput[]
        | Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput[];
    connectOrCreate?:
        | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput
        | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput[];
    upsert?:
        | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutWorkoutTemplateInput
        | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutWorkoutTemplateInput[];
    createMany?: Prisma.RoutineTemplateCreateManyWorkoutTemplateInputEnvelope;
    set?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    disconnect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    delete?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    connect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    update?:
        | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutWorkoutTemplateInput
        | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutWorkoutTemplateInput[];
    updateMany?:
        | Prisma.RoutineTemplateUpdateManyWithWhereWithoutWorkoutTemplateInput
        | Prisma.RoutineTemplateUpdateManyWithWhereWithoutWorkoutTemplateInput[];
    deleteMany?:
        | Prisma.RoutineTemplateScalarWhereInput
        | Prisma.RoutineTemplateScalarWhereInput[];
};

export type RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateNestedInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput,
                  Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput
              >
            | Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput[]
            | Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput[];
        connectOrCreate?:
            | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput
            | Prisma.RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput[];
        upsert?:
            | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutWorkoutTemplateInput
            | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutWorkoutTemplateInput[];
        createMany?: Prisma.RoutineTemplateCreateManyWorkoutTemplateInputEnvelope;
        set?:
            | Prisma.RoutineTemplateWhereUniqueInput
            | Prisma.RoutineTemplateWhereUniqueInput[];
        disconnect?:
            | Prisma.RoutineTemplateWhereUniqueInput
            | Prisma.RoutineTemplateWhereUniqueInput[];
        delete?:
            | Prisma.RoutineTemplateWhereUniqueInput
            | Prisma.RoutineTemplateWhereUniqueInput[];
        connect?:
            | Prisma.RoutineTemplateWhereUniqueInput
            | Prisma.RoutineTemplateWhereUniqueInput[];
        update?:
            | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutWorkoutTemplateInput
            | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutWorkoutTemplateInput[];
        updateMany?:
            | Prisma.RoutineTemplateUpdateManyWithWhereWithoutWorkoutTemplateInput
            | Prisma.RoutineTemplateUpdateManyWithWhereWithoutWorkoutTemplateInput[];
        deleteMany?:
            | Prisma.RoutineTemplateScalarWhereInput
            | Prisma.RoutineTemplateScalarWhereInput[];
    };

export type RoutineTemplateCreateNestedManyWithoutRoutineInput = {
    create?:
        | Prisma.XOR<
              Prisma.RoutineTemplateCreateWithoutRoutineInput,
              Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput
          >
        | Prisma.RoutineTemplateCreateWithoutRoutineInput[]
        | Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput[];
    connectOrCreate?:
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput[];
    createMany?: Prisma.RoutineTemplateCreateManyRoutineInputEnvelope;
    connect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
};

export type RoutineTemplateUncheckedCreateNestedManyWithoutRoutineInput = {
    create?:
        | Prisma.XOR<
              Prisma.RoutineTemplateCreateWithoutRoutineInput,
              Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput
          >
        | Prisma.RoutineTemplateCreateWithoutRoutineInput[]
        | Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput[];
    connectOrCreate?:
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput[];
    createMany?: Prisma.RoutineTemplateCreateManyRoutineInputEnvelope;
    connect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
};

export type RoutineTemplateUpdateManyWithoutRoutineNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.RoutineTemplateCreateWithoutRoutineInput,
              Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput
          >
        | Prisma.RoutineTemplateCreateWithoutRoutineInput[]
        | Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput[];
    connectOrCreate?:
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput[];
    upsert?:
        | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutRoutineInput
        | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutRoutineInput[];
    createMany?: Prisma.RoutineTemplateCreateManyRoutineInputEnvelope;
    set?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    disconnect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    delete?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    connect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    update?:
        | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutRoutineInput
        | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutRoutineInput[];
    updateMany?:
        | Prisma.RoutineTemplateUpdateManyWithWhereWithoutRoutineInput
        | Prisma.RoutineTemplateUpdateManyWithWhereWithoutRoutineInput[];
    deleteMany?:
        | Prisma.RoutineTemplateScalarWhereInput
        | Prisma.RoutineTemplateScalarWhereInput[];
};

export type RoutineTemplateUncheckedUpdateManyWithoutRoutineNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.RoutineTemplateCreateWithoutRoutineInput,
              Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput
          >
        | Prisma.RoutineTemplateCreateWithoutRoutineInput[]
        | Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput[];
    connectOrCreate?:
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput
        | Prisma.RoutineTemplateCreateOrConnectWithoutRoutineInput[];
    upsert?:
        | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutRoutineInput
        | Prisma.RoutineTemplateUpsertWithWhereUniqueWithoutRoutineInput[];
    createMany?: Prisma.RoutineTemplateCreateManyRoutineInputEnvelope;
    set?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    disconnect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    delete?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    connect?:
        | Prisma.RoutineTemplateWhereUniqueInput
        | Prisma.RoutineTemplateWhereUniqueInput[];
    update?:
        | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutRoutineInput
        | Prisma.RoutineTemplateUpdateWithWhereUniqueWithoutRoutineInput[];
    updateMany?:
        | Prisma.RoutineTemplateUpdateManyWithWhereWithoutRoutineInput
        | Prisma.RoutineTemplateUpdateManyWithWhereWithoutRoutineInput[];
    deleteMany?:
        | Prisma.RoutineTemplateScalarWhereInput
        | Prisma.RoutineTemplateScalarWhereInput[];
};

export type RoutineTemplateCreateWithoutWorkoutTemplateInput = {
    id?: string;
    dayOfWeek?: number | null;
    routine: Prisma.RoutineCreateNestedOneWithoutTemplatesInput;
};

export type RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput = {
    id?: string;
    routineId: string;
    dayOfWeek?: number | null;
};

export type RoutineTemplateCreateOrConnectWithoutWorkoutTemplateInput = {
    where: Prisma.RoutineTemplateWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput,
        Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput
    >;
};

export type RoutineTemplateCreateManyWorkoutTemplateInputEnvelope = {
    data:
        | Prisma.RoutineTemplateCreateManyWorkoutTemplateInput
        | Prisma.RoutineTemplateCreateManyWorkoutTemplateInput[];
    skipDuplicates?: boolean;
};

export type RoutineTemplateUpsertWithWhereUniqueWithoutWorkoutTemplateInput = {
    where: Prisma.RoutineTemplateWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.RoutineTemplateUpdateWithoutWorkoutTemplateInput,
        Prisma.RoutineTemplateUncheckedUpdateWithoutWorkoutTemplateInput
    >;
    create: Prisma.XOR<
        Prisma.RoutineTemplateCreateWithoutWorkoutTemplateInput,
        Prisma.RoutineTemplateUncheckedCreateWithoutWorkoutTemplateInput
    >;
};

export type RoutineTemplateUpdateWithWhereUniqueWithoutWorkoutTemplateInput = {
    where: Prisma.RoutineTemplateWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateWithoutWorkoutTemplateInput,
        Prisma.RoutineTemplateUncheckedUpdateWithoutWorkoutTemplateInput
    >;
};

export type RoutineTemplateUpdateManyWithWhereWithoutWorkoutTemplateInput = {
    where: Prisma.RoutineTemplateScalarWhereInput;
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateManyMutationInput,
        Prisma.RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateInput
    >;
};

export type RoutineTemplateScalarWhereInput = {
    AND?:
        | Prisma.RoutineTemplateScalarWhereInput
        | Prisma.RoutineTemplateScalarWhereInput[];
    OR?: Prisma.RoutineTemplateScalarWhereInput[];
    NOT?:
        | Prisma.RoutineTemplateScalarWhereInput
        | Prisma.RoutineTemplateScalarWhereInput[];
    id?: Prisma.StringFilter<'RoutineTemplate'> | string;
    routineId?: Prisma.StringFilter<'RoutineTemplate'> | string;
    workoutTemplateId?: Prisma.StringFilter<'RoutineTemplate'> | string;
    dayOfWeek?: Prisma.IntNullableFilter<'RoutineTemplate'> | number | null;
};

export type RoutineTemplateCreateWithoutRoutineInput = {
    id?: string;
    dayOfWeek?: number | null;
    workoutTemplate: Prisma.WorkoutTemplateCreateNestedOneWithoutRoutinesInput;
};

export type RoutineTemplateUncheckedCreateWithoutRoutineInput = {
    id?: string;
    workoutTemplateId: string;
    dayOfWeek?: number | null;
};

export type RoutineTemplateCreateOrConnectWithoutRoutineInput = {
    where: Prisma.RoutineTemplateWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.RoutineTemplateCreateWithoutRoutineInput,
        Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput
    >;
};

export type RoutineTemplateCreateManyRoutineInputEnvelope = {
    data:
        | Prisma.RoutineTemplateCreateManyRoutineInput
        | Prisma.RoutineTemplateCreateManyRoutineInput[];
    skipDuplicates?: boolean;
};

export type RoutineTemplateUpsertWithWhereUniqueWithoutRoutineInput = {
    where: Prisma.RoutineTemplateWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.RoutineTemplateUpdateWithoutRoutineInput,
        Prisma.RoutineTemplateUncheckedUpdateWithoutRoutineInput
    >;
    create: Prisma.XOR<
        Prisma.RoutineTemplateCreateWithoutRoutineInput,
        Prisma.RoutineTemplateUncheckedCreateWithoutRoutineInput
    >;
};

export type RoutineTemplateUpdateWithWhereUniqueWithoutRoutineInput = {
    where: Prisma.RoutineTemplateWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateWithoutRoutineInput,
        Prisma.RoutineTemplateUncheckedUpdateWithoutRoutineInput
    >;
};

export type RoutineTemplateUpdateManyWithWhereWithoutRoutineInput = {
    where: Prisma.RoutineTemplateScalarWhereInput;
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateManyMutationInput,
        Prisma.RoutineTemplateUncheckedUpdateManyWithoutRoutineInput
    >;
};

export type RoutineTemplateCreateManyWorkoutTemplateInput = {
    id?: string;
    routineId: string;
    dayOfWeek?: number | null;
};

export type RoutineTemplateUpdateWithoutWorkoutTemplateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
    routine?: Prisma.RoutineUpdateOneRequiredWithoutTemplatesNestedInput;
};

export type RoutineTemplateUncheckedUpdateWithoutWorkoutTemplateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    routineId?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    routineId?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateCreateManyRoutineInput = {
    id?: string;
    workoutTemplateId: string;
    dayOfWeek?: number | null;
};

export type RoutineTemplateUpdateWithoutRoutineInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
    workoutTemplate?: Prisma.WorkoutTemplateUpdateOneRequiredWithoutRoutinesNestedInput;
};

export type RoutineTemplateUncheckedUpdateWithoutRoutineInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateUncheckedUpdateManyWithoutRoutineInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?: Prisma.StringFieldUpdateOperationsInput | string;
    dayOfWeek?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type RoutineTemplateSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        routineId?: boolean;
        workoutTemplateId?: boolean;
        dayOfWeek?: boolean;
        routine?: boolean | Prisma.RoutineDefaultArgs<ExtArgs>;
        workoutTemplate?: boolean | Prisma.WorkoutTemplateDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['routineTemplate']
>;

export type RoutineTemplateSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        routineId?: boolean;
        workoutTemplateId?: boolean;
        dayOfWeek?: boolean;
        routine?: boolean | Prisma.RoutineDefaultArgs<ExtArgs>;
        workoutTemplate?: boolean | Prisma.WorkoutTemplateDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['routineTemplate']
>;

export type RoutineTemplateSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        routineId?: boolean;
        workoutTemplateId?: boolean;
        dayOfWeek?: boolean;
        routine?: boolean | Prisma.RoutineDefaultArgs<ExtArgs>;
        workoutTemplate?: boolean | Prisma.WorkoutTemplateDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['routineTemplate']
>;

export type RoutineTemplateSelectScalar = {
    id?: boolean;
    routineId?: boolean;
    workoutTemplateId?: boolean;
    dayOfWeek?: boolean;
};

export type RoutineTemplateOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    'id' | 'routineId' | 'workoutTemplateId' | 'dayOfWeek',
    ExtArgs['result']['routineTemplate']
>;
export type RoutineTemplateInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    routine?: boolean | Prisma.RoutineDefaultArgs<ExtArgs>;
    workoutTemplate?: boolean | Prisma.WorkoutTemplateDefaultArgs<ExtArgs>;
};
export type RoutineTemplateIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    routine?: boolean | Prisma.RoutineDefaultArgs<ExtArgs>;
    workoutTemplate?: boolean | Prisma.WorkoutTemplateDefaultArgs<ExtArgs>;
};
export type RoutineTemplateIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    routine?: boolean | Prisma.RoutineDefaultArgs<ExtArgs>;
    workoutTemplate?: boolean | Prisma.WorkoutTemplateDefaultArgs<ExtArgs>;
};

export type $RoutineTemplatePayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: 'RoutineTemplate';
    objects: {
        routine: Prisma.$RoutinePayload<ExtArgs>;
        workoutTemplate: Prisma.$WorkoutTemplatePayload<ExtArgs>;
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            routineId: string;
            workoutTemplateId: string;
            dayOfWeek: number | null;
        },
        ExtArgs['result']['routineTemplate']
    >;
    composites: {};
};

export type RoutineTemplateGetPayload<
    S extends boolean | null | undefined | RoutineTemplateDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$RoutineTemplatePayload, S>;

export type RoutineTemplateCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<
    RoutineTemplateFindManyArgs,
    'select' | 'include' | 'distinct' | 'omit'
> & {
    select?: RoutineTemplateCountAggregateInputType | true;
};

export interface RoutineTemplateDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>['model']['RoutineTemplate'];
        meta: { name: 'RoutineTemplate' };
    };
    /**
     * Find zero or one RoutineTemplate that matches the filter.
     * @param {RoutineTemplateFindUniqueArgs} args - Arguments to find a RoutineTemplate
     * @example
     * // Get one RoutineTemplate
     * const routineTemplate = await prisma.routineTemplate.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends RoutineTemplateFindUniqueArgs>(
        args: Prisma.SelectSubset<T, RoutineTemplateFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'findUnique',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one RoutineTemplate that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {RoutineTemplateFindUniqueOrThrowArgs} args - Arguments to find a RoutineTemplate
     * @example
     * // Get one RoutineTemplate
     * const routineTemplate = await prisma.routineTemplate.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends RoutineTemplateFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<
            T,
            RoutineTemplateFindUniqueOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first RoutineTemplate that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateFindFirstArgs} args - Arguments to find a RoutineTemplate
     * @example
     * // Get one RoutineTemplate
     * const routineTemplate = await prisma.routineTemplate.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends RoutineTemplateFindFirstArgs>(
        args?: Prisma.SelectSubset<T, RoutineTemplateFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'findFirst',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first RoutineTemplate that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateFindFirstOrThrowArgs} args - Arguments to find a RoutineTemplate
     * @example
     * // Get one RoutineTemplate
     * const routineTemplate = await prisma.routineTemplate.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends RoutineTemplateFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<
            T,
            RoutineTemplateFindFirstOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'findFirstOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more RoutineTemplates that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all RoutineTemplates
     * const routineTemplates = await prisma.routineTemplate.findMany()
     *
     * // Get first 10 RoutineTemplates
     * const routineTemplates = await prisma.routineTemplate.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const routineTemplateWithIdOnly = await prisma.routineTemplate.findMany({ select: { id: true } })
     *
     */
    findMany<T extends RoutineTemplateFindManyArgs>(
        args?: Prisma.SelectSubset<T, RoutineTemplateFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'findMany',
            GlobalOmitOptions
        >
    >;

    /**
     * Create a RoutineTemplate.
     * @param {RoutineTemplateCreateArgs} args - Arguments to create a RoutineTemplate.
     * @example
     * // Create one RoutineTemplate
     * const RoutineTemplate = await prisma.routineTemplate.create({
     *   data: {
     *     // ... data to create a RoutineTemplate
     *   }
     * })
     *
     */
    create<T extends RoutineTemplateCreateArgs>(
        args: Prisma.SelectSubset<T, RoutineTemplateCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'create',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many RoutineTemplates.
     * @param {RoutineTemplateCreateManyArgs} args - Arguments to create many RoutineTemplates.
     * @example
     * // Create many RoutineTemplates
     * const routineTemplate = await prisma.routineTemplate.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends RoutineTemplateCreateManyArgs>(
        args?: Prisma.SelectSubset<T, RoutineTemplateCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many RoutineTemplates and returns the data saved in the database.
     * @param {RoutineTemplateCreateManyAndReturnArgs} args - Arguments to create many RoutineTemplates.
     * @example
     * // Create many RoutineTemplates
     * const routineTemplate = await prisma.routineTemplate.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many RoutineTemplates and only return the `id`
     * const routineTemplateWithIdOnly = await prisma.routineTemplate.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends RoutineTemplateCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<
            T,
            RoutineTemplateCreateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'createManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a RoutineTemplate.
     * @param {RoutineTemplateDeleteArgs} args - Arguments to delete one RoutineTemplate.
     * @example
     * // Delete one RoutineTemplate
     * const RoutineTemplate = await prisma.routineTemplate.delete({
     *   where: {
     *     // ... filter to delete one RoutineTemplate
     *   }
     * })
     *
     */
    delete<T extends RoutineTemplateDeleteArgs>(
        args: Prisma.SelectSubset<T, RoutineTemplateDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'delete',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one RoutineTemplate.
     * @param {RoutineTemplateUpdateArgs} args - Arguments to update one RoutineTemplate.
     * @example
     * // Update one RoutineTemplate
     * const routineTemplate = await prisma.routineTemplate.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends RoutineTemplateUpdateArgs>(
        args: Prisma.SelectSubset<T, RoutineTemplateUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'update',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more RoutineTemplates.
     * @param {RoutineTemplateDeleteManyArgs} args - Arguments to filter RoutineTemplates to delete.
     * @example
     * // Delete a few RoutineTemplates
     * const { count } = await prisma.routineTemplate.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends RoutineTemplateDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, RoutineTemplateDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more RoutineTemplates.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many RoutineTemplates
     * const routineTemplate = await prisma.routineTemplate.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends RoutineTemplateUpdateManyArgs>(
        args: Prisma.SelectSubset<T, RoutineTemplateUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more RoutineTemplates and returns the data updated in the database.
     * @param {RoutineTemplateUpdateManyAndReturnArgs} args - Arguments to update many RoutineTemplates.
     * @example
     * // Update many RoutineTemplates
     * const routineTemplate = await prisma.routineTemplate.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more RoutineTemplates and only return the `id`
     * const routineTemplateWithIdOnly = await prisma.routineTemplate.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends RoutineTemplateUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<
            T,
            RoutineTemplateUpdateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'updateManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one RoutineTemplate.
     * @param {RoutineTemplateUpsertArgs} args - Arguments to update or create a RoutineTemplate.
     * @example
     * // Update or create a RoutineTemplate
     * const routineTemplate = await prisma.routineTemplate.upsert({
     *   create: {
     *     // ... data to create a RoutineTemplate
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the RoutineTemplate we want to update
     *   }
     * })
     */
    upsert<T extends RoutineTemplateUpsertArgs>(
        args: Prisma.SelectSubset<T, RoutineTemplateUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$RoutineTemplatePayload<ExtArgs>,
            T,
            'upsert',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of RoutineTemplates.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateCountArgs} args - Arguments to filter RoutineTemplates to count.
     * @example
     * // Count the number of RoutineTemplates
     * const count = await prisma.routineTemplate.count({
     *   where: {
     *     // ... the filter for the RoutineTemplates we want to count
     *   }
     * })
     **/
    count<T extends RoutineTemplateCountArgs>(
        args?: Prisma.Subset<T, RoutineTemplateCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<
                      T['select'],
                      RoutineTemplateCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a RoutineTemplate.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends RoutineTemplateAggregateArgs>(
        args: Prisma.Subset<T, RoutineTemplateAggregateArgs>,
    ): Prisma.PrismaPromise<GetRoutineTemplateAggregateType<T>>;

    /**
     * Group by RoutineTemplate.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {RoutineTemplateGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends RoutineTemplateGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: RoutineTemplateGroupByArgs['orderBy'] }
            : { orderBy?: RoutineTemplateGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                'Field ',
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : 'take' extends Prisma.Keys<T>
                ? 'orderBy' extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : 'skip' extends Prisma.Keys<T>
                  ? 'orderBy' extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<
            T,
            RoutineTemplateGroupByArgs,
            OrderByArg
        > &
            InputErrors,
    ): {} extends InputErrors
        ? GetRoutineTemplateGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the RoutineTemplate model
     */
    readonly fields: RoutineTemplateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RoutineTemplate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RoutineTemplateClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: 'PrismaPromise';
    routine<T extends Prisma.RoutineDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.RoutineDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__RoutineClient<
        | runtime.Types.Result.GetResult<
              Prisma.$RoutinePayload<ExtArgs>,
              T,
              'findUniqueOrThrow',
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    workoutTemplate<T extends Prisma.WorkoutTemplateDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutTemplateDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        | runtime.Types.Result.GetResult<
              Prisma.$WorkoutTemplatePayload<ExtArgs>,
              T,
              'findUniqueOrThrow',
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the RoutineTemplate model
 */
export interface RoutineTemplateFieldRefs {
    readonly id: Prisma.FieldRef<'RoutineTemplate', 'String'>;
    readonly routineId: Prisma.FieldRef<'RoutineTemplate', 'String'>;
    readonly workoutTemplateId: Prisma.FieldRef<'RoutineTemplate', 'String'>;
    readonly dayOfWeek: Prisma.FieldRef<'RoutineTemplate', 'Int'>;
}

// Custom InputTypes
/**
 * RoutineTemplate findUnique
 */
export type RoutineTemplateFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which RoutineTemplate to fetch.
     */
    where: Prisma.RoutineTemplateWhereUniqueInput;
};

/**
 * RoutineTemplate findUniqueOrThrow
 */
export type RoutineTemplateFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which RoutineTemplate to fetch.
     */
    where: Prisma.RoutineTemplateWhereUniqueInput;
};

/**
 * RoutineTemplate findFirst
 */
export type RoutineTemplateFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which RoutineTemplate to fetch.
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of RoutineTemplates to fetch.
     */
    orderBy?:
        | Prisma.RoutineTemplateOrderByWithRelationInput
        | Prisma.RoutineTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for RoutineTemplates.
     */
    cursor?: Prisma.RoutineTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` RoutineTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` RoutineTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of RoutineTemplates.
     */
    distinct?:
        | Prisma.RoutineTemplateScalarFieldEnum
        | Prisma.RoutineTemplateScalarFieldEnum[];
};

/**
 * RoutineTemplate findFirstOrThrow
 */
export type RoutineTemplateFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which RoutineTemplate to fetch.
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of RoutineTemplates to fetch.
     */
    orderBy?:
        | Prisma.RoutineTemplateOrderByWithRelationInput
        | Prisma.RoutineTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for RoutineTemplates.
     */
    cursor?: Prisma.RoutineTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` RoutineTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` RoutineTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of RoutineTemplates.
     */
    distinct?:
        | Prisma.RoutineTemplateScalarFieldEnum
        | Prisma.RoutineTemplateScalarFieldEnum[];
};

/**
 * RoutineTemplate findMany
 */
export type RoutineTemplateFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which RoutineTemplates to fetch.
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of RoutineTemplates to fetch.
     */
    orderBy?:
        | Prisma.RoutineTemplateOrderByWithRelationInput
        | Prisma.RoutineTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing RoutineTemplates.
     */
    cursor?: Prisma.RoutineTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` RoutineTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` RoutineTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of RoutineTemplates.
     */
    distinct?:
        | Prisma.RoutineTemplateScalarFieldEnum
        | Prisma.RoutineTemplateScalarFieldEnum[];
};

/**
 * RoutineTemplate create
 */
export type RoutineTemplateCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * The data needed to create a RoutineTemplate.
     */
    data: Prisma.XOR<
        Prisma.RoutineTemplateCreateInput,
        Prisma.RoutineTemplateUncheckedCreateInput
    >;
};

/**
 * RoutineTemplate createMany
 */
export type RoutineTemplateCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many RoutineTemplates.
     */
    data:
        | Prisma.RoutineTemplateCreateManyInput
        | Prisma.RoutineTemplateCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * RoutineTemplate createManyAndReturn
 */
export type RoutineTemplateCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * The data used to create many RoutineTemplates.
     */
    data:
        | Prisma.RoutineTemplateCreateManyInput
        | Prisma.RoutineTemplateCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * RoutineTemplate update
 */
export type RoutineTemplateUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * The data needed to update a RoutineTemplate.
     */
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateInput,
        Prisma.RoutineTemplateUncheckedUpdateInput
    >;
    /**
     * Choose, which RoutineTemplate to update.
     */
    where: Prisma.RoutineTemplateWhereUniqueInput;
};

/**
 * RoutineTemplate updateMany
 */
export type RoutineTemplateUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update RoutineTemplates.
     */
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateManyMutationInput,
        Prisma.RoutineTemplateUncheckedUpdateManyInput
    >;
    /**
     * Filter which RoutineTemplates to update
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * Limit how many RoutineTemplates to update.
     */
    limit?: number;
};

/**
 * RoutineTemplate updateManyAndReturn
 */
export type RoutineTemplateUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * The data used to update RoutineTemplates.
     */
    data: Prisma.XOR<
        Prisma.RoutineTemplateUpdateManyMutationInput,
        Prisma.RoutineTemplateUncheckedUpdateManyInput
    >;
    /**
     * Filter which RoutineTemplates to update
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * Limit how many RoutineTemplates to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * RoutineTemplate upsert
 */
export type RoutineTemplateUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * The filter to search for the RoutineTemplate to update in case it exists.
     */
    where: Prisma.RoutineTemplateWhereUniqueInput;
    /**
     * In case the RoutineTemplate found by the `where` argument doesn't exist, create a new RoutineTemplate with this data.
     */
    create: Prisma.XOR<
        Prisma.RoutineTemplateCreateInput,
        Prisma.RoutineTemplateUncheckedCreateInput
    >;
    /**
     * In case the RoutineTemplate was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.RoutineTemplateUpdateInput,
        Prisma.RoutineTemplateUncheckedUpdateInput
    >;
};

/**
 * RoutineTemplate delete
 */
export type RoutineTemplateDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    /**
     * Filter which RoutineTemplate to delete.
     */
    where: Prisma.RoutineTemplateWhereUniqueInput;
};

/**
 * RoutineTemplate deleteMany
 */
export type RoutineTemplateDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which RoutineTemplates to delete
     */
    where?: Prisma.RoutineTemplateWhereInput;
    /**
     * Limit how many RoutineTemplates to delete.
     */
    limit?: number;
};

/**
 * RoutineTemplate without action
 */
export type RoutineTemplateDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
};
