/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WorkoutSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model WorkoutSession
 *
 */
export type WorkoutSessionModel =
    runtime.Types.Result.DefaultSelection<Prisma.$WorkoutSessionPayload>;

export type AggregateWorkoutSession = {
    _count: WorkoutSessionCountAggregateOutputType | null;
    _min: WorkoutSessionMinAggregateOutputType | null;
    _max: WorkoutSessionMaxAggregateOutputType | null;
};

export type WorkoutSessionMinAggregateOutputType = {
    id: string | null;
    userId: string | null;
    workoutTemplateId: string | null;
    startedAt: Date | null;
    finishedAt: Date | null;
};

export type WorkoutSessionMaxAggregateOutputType = {
    id: string | null;
    userId: string | null;
    workoutTemplateId: string | null;
    startedAt: Date | null;
    finishedAt: Date | null;
};

export type WorkoutSessionCountAggregateOutputType = {
    id: number;
    userId: number;
    workoutTemplateId: number;
    startedAt: number;
    finishedAt: number;
    _all: number;
};

export type WorkoutSessionMinAggregateInputType = {
    id?: true;
    userId?: true;
    workoutTemplateId?: true;
    startedAt?: true;
    finishedAt?: true;
};

export type WorkoutSessionMaxAggregateInputType = {
    id?: true;
    userId?: true;
    workoutTemplateId?: true;
    startedAt?: true;
    finishedAt?: true;
};

export type WorkoutSessionCountAggregateInputType = {
    id?: true;
    userId?: true;
    workoutTemplateId?: true;
    startedAt?: true;
    finishedAt?: true;
    _all?: true;
};

export type WorkoutSessionAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which WorkoutSession to aggregate.
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessions to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionOrderByWithRelationInput
        | Prisma.WorkoutSessionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.WorkoutSessionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned WorkoutSessions
     **/
    _count?: true | WorkoutSessionCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: WorkoutSessionMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: WorkoutSessionMaxAggregateInputType;
};

export type GetWorkoutSessionAggregateType<
    T extends WorkoutSessionAggregateArgs,
> = {
    [P in keyof T & keyof AggregateWorkoutSession]: P extends '_count' | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateWorkoutSession[P]>
        : Prisma.GetScalarType<T[P], AggregateWorkoutSession[P]>;
};

export type WorkoutSessionGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.WorkoutSessionWhereInput;
    orderBy?:
        | Prisma.WorkoutSessionOrderByWithAggregationInput
        | Prisma.WorkoutSessionOrderByWithAggregationInput[];
    by:
        | Prisma.WorkoutSessionScalarFieldEnum[]
        | Prisma.WorkoutSessionScalarFieldEnum;
    having?: Prisma.WorkoutSessionScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: WorkoutSessionCountAggregateInputType | true;
    _min?: WorkoutSessionMinAggregateInputType;
    _max?: WorkoutSessionMaxAggregateInputType;
};

export type WorkoutSessionGroupByOutputType = {
    id: string;
    userId: string;
    workoutTemplateId: string | null;
    startedAt: Date;
    finishedAt: Date | null;
    _count: WorkoutSessionCountAggregateOutputType | null;
    _min: WorkoutSessionMinAggregateOutputType | null;
    _max: WorkoutSessionMaxAggregateOutputType | null;
};

export type GetWorkoutSessionGroupByPayload<
    T extends WorkoutSessionGroupByArgs,
> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<WorkoutSessionGroupByOutputType, T['by']> & {
            [P in keyof T &
                keyof WorkoutSessionGroupByOutputType]: P extends '_count'
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<
                          T[P],
                          WorkoutSessionGroupByOutputType[P]
                      >
                : Prisma.GetScalarType<
                      T[P],
                      WorkoutSessionGroupByOutputType[P]
                  >;
        }
    >
>;

export type WorkoutSessionWhereInput = {
    AND?: Prisma.WorkoutSessionWhereInput | Prisma.WorkoutSessionWhereInput[];
    OR?: Prisma.WorkoutSessionWhereInput[];
    NOT?: Prisma.WorkoutSessionWhereInput | Prisma.WorkoutSessionWhereInput[];
    id?: Prisma.StringFilter<'WorkoutSession'> | string;
    userId?: Prisma.StringFilter<'WorkoutSession'> | string;
    workoutTemplateId?:
        | Prisma.StringNullableFilter<'WorkoutSession'>
        | string
        | null;
    startedAt?: Prisma.DateTimeFilter<'WorkoutSession'> | Date | string;
    finishedAt?:
        | Prisma.DateTimeNullableFilter<'WorkoutSession'>
        | Date
        | string
        | null;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    workoutTemplate?: Prisma.XOR<
        Prisma.WorkoutTemplateNullableScalarRelationFilter,
        Prisma.WorkoutTemplateWhereInput
    > | null;
    exercises?: Prisma.WorkoutSessionExerciseListRelationFilter;
};

export type WorkoutSessionOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrderInput | Prisma.SortOrder;
    startedAt?: Prisma.SortOrder;
    finishedAt?: Prisma.SortOrderInput | Prisma.SortOrder;
    user?: Prisma.UserOrderByWithRelationInput;
    workoutTemplate?: Prisma.WorkoutTemplateOrderByWithRelationInput;
    exercises?: Prisma.WorkoutSessionExerciseOrderByRelationAggregateInput;
};

export type WorkoutSessionWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?:
            | Prisma.WorkoutSessionWhereInput
            | Prisma.WorkoutSessionWhereInput[];
        OR?: Prisma.WorkoutSessionWhereInput[];
        NOT?:
            | Prisma.WorkoutSessionWhereInput
            | Prisma.WorkoutSessionWhereInput[];
        userId?: Prisma.StringFilter<'WorkoutSession'> | string;
        workoutTemplateId?:
            | Prisma.StringNullableFilter<'WorkoutSession'>
            | string
            | null;
        startedAt?: Prisma.DateTimeFilter<'WorkoutSession'> | Date | string;
        finishedAt?:
            | Prisma.DateTimeNullableFilter<'WorkoutSession'>
            | Date
            | string
            | null;
        user?: Prisma.XOR<
            Prisma.UserScalarRelationFilter,
            Prisma.UserWhereInput
        >;
        workoutTemplate?: Prisma.XOR<
            Prisma.WorkoutTemplateNullableScalarRelationFilter,
            Prisma.WorkoutTemplateWhereInput
        > | null;
        exercises?: Prisma.WorkoutSessionExerciseListRelationFilter;
    },
    'id'
>;

export type WorkoutSessionOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrderInput | Prisma.SortOrder;
    startedAt?: Prisma.SortOrder;
    finishedAt?: Prisma.SortOrderInput | Prisma.SortOrder;
    _count?: Prisma.WorkoutSessionCountOrderByAggregateInput;
    _max?: Prisma.WorkoutSessionMaxOrderByAggregateInput;
    _min?: Prisma.WorkoutSessionMinOrderByAggregateInput;
};

export type WorkoutSessionScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.WorkoutSessionScalarWhereWithAggregatesInput
        | Prisma.WorkoutSessionScalarWhereWithAggregatesInput[];
    OR?: Prisma.WorkoutSessionScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.WorkoutSessionScalarWhereWithAggregatesInput
        | Prisma.WorkoutSessionScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<'WorkoutSession'> | string;
    userId?: Prisma.StringWithAggregatesFilter<'WorkoutSession'> | string;
    workoutTemplateId?:
        | Prisma.StringNullableWithAggregatesFilter<'WorkoutSession'>
        | string
        | null;
    startedAt?:
        | Prisma.DateTimeWithAggregatesFilter<'WorkoutSession'>
        | Date
        | string;
    finishedAt?:
        | Prisma.DateTimeNullableWithAggregatesFilter<'WorkoutSession'>
        | Date
        | string
        | null;
};

export type WorkoutSessionCreateInput = {
    id?: string;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    user: Prisma.UserCreateNestedOneWithoutSessionsInput;
    workoutTemplate?: Prisma.WorkoutTemplateCreateNestedOneWithoutSessionsInput;
    exercises?: Prisma.WorkoutSessionExerciseCreateNestedManyWithoutSessionInput;
};

export type WorkoutSessionUncheckedCreateInput = {
    id?: string;
    userId: string;
    workoutTemplateId?: string | null;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    exercises?: Prisma.WorkoutSessionExerciseUncheckedCreateNestedManyWithoutSessionInput;
};

export type WorkoutSessionUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput;
    workoutTemplate?: Prisma.WorkoutTemplateUpdateOneWithoutSessionsNestedInput;
    exercises?: Prisma.WorkoutSessionExerciseUpdateManyWithoutSessionNestedInput;
};

export type WorkoutSessionUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    exercises?: Prisma.WorkoutSessionExerciseUncheckedUpdateManyWithoutSessionNestedInput;
};

export type WorkoutSessionCreateManyInput = {
    id?: string;
    userId: string;
    workoutTemplateId?: string | null;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
};

export type WorkoutSessionUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
};

export type WorkoutSessionUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
};

export type WorkoutSessionListRelationFilter = {
    every?: Prisma.WorkoutSessionWhereInput;
    some?: Prisma.WorkoutSessionWhereInput;
    none?: Prisma.WorkoutSessionWhereInput;
};

export type WorkoutSessionOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type WorkoutSessionCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    startedAt?: Prisma.SortOrder;
    finishedAt?: Prisma.SortOrder;
};

export type WorkoutSessionMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    startedAt?: Prisma.SortOrder;
    finishedAt?: Prisma.SortOrder;
};

export type WorkoutSessionMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    workoutTemplateId?: Prisma.SortOrder;
    startedAt?: Prisma.SortOrder;
    finishedAt?: Prisma.SortOrder;
};

export type WorkoutSessionScalarRelationFilter = {
    is?: Prisma.WorkoutSessionWhereInput;
    isNot?: Prisma.WorkoutSessionWhereInput;
};

export type WorkoutSessionCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionCreateWithoutUserInput,
              Prisma.WorkoutSessionUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutSessionCreateWithoutUserInput[]
        | Prisma.WorkoutSessionUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.WorkoutSessionCreateManyUserInputEnvelope;
    connect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
};

export type WorkoutSessionUncheckedCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionCreateWithoutUserInput,
              Prisma.WorkoutSessionUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutSessionCreateWithoutUserInput[]
        | Prisma.WorkoutSessionUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.WorkoutSessionCreateManyUserInputEnvelope;
    connect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
};

export type WorkoutSessionUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionCreateWithoutUserInput,
              Prisma.WorkoutSessionUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutSessionCreateWithoutUserInput[]
        | Prisma.WorkoutSessionUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.WorkoutSessionCreateManyUserInputEnvelope;
    set?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    update?:
        | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.WorkoutSessionUpdateManyWithWhereWithoutUserInput
        | Prisma.WorkoutSessionUpdateManyWithWhereWithoutUserInput[];
    deleteMany?:
        | Prisma.WorkoutSessionScalarWhereInput
        | Prisma.WorkoutSessionScalarWhereInput[];
};

export type WorkoutSessionUncheckedUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionCreateWithoutUserInput,
              Prisma.WorkoutSessionUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutSessionCreateWithoutUserInput[]
        | Prisma.WorkoutSessionUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput
        | Prisma.WorkoutSessionCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.WorkoutSessionCreateManyUserInputEnvelope;
    set?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    update?:
        | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.WorkoutSessionUpdateManyWithWhereWithoutUserInput
        | Prisma.WorkoutSessionUpdateManyWithWhereWithoutUserInput[];
    deleteMany?:
        | Prisma.WorkoutSessionScalarWhereInput
        | Prisma.WorkoutSessionScalarWhereInput[];
};

export type WorkoutSessionCreateNestedManyWithoutWorkoutTemplateInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput,
              Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput
          >
        | Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput[]
        | Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput
        | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput[];
    createMany?: Prisma.WorkoutSessionCreateManyWorkoutTemplateInputEnvelope;
    connect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
};

export type WorkoutSessionUncheckedCreateNestedManyWithoutWorkoutTemplateInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput,
                  Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput
              >
            | Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput[]
            | Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput[];
        connectOrCreate?:
            | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput
            | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput[];
        createMany?: Prisma.WorkoutSessionCreateManyWorkoutTemplateInputEnvelope;
        connect?:
            | Prisma.WorkoutSessionWhereUniqueInput
            | Prisma.WorkoutSessionWhereUniqueInput[];
    };

export type WorkoutSessionUpdateManyWithoutWorkoutTemplateNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput,
              Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput
          >
        | Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput[]
        | Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput
        | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput[];
    upsert?:
        | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutWorkoutTemplateInput
        | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutWorkoutTemplateInput[];
    createMany?: Prisma.WorkoutSessionCreateManyWorkoutTemplateInputEnvelope;
    set?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutSessionWhereUniqueInput
        | Prisma.WorkoutSessionWhereUniqueInput[];
    update?:
        | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutWorkoutTemplateInput
        | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutWorkoutTemplateInput[];
    updateMany?:
        | Prisma.WorkoutSessionUpdateManyWithWhereWithoutWorkoutTemplateInput
        | Prisma.WorkoutSessionUpdateManyWithWhereWithoutWorkoutTemplateInput[];
    deleteMany?:
        | Prisma.WorkoutSessionScalarWhereInput
        | Prisma.WorkoutSessionScalarWhereInput[];
};

export type WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateNestedInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput,
                  Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput
              >
            | Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput[]
            | Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput[];
        connectOrCreate?:
            | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput
            | Prisma.WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput[];
        upsert?:
            | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutWorkoutTemplateInput
            | Prisma.WorkoutSessionUpsertWithWhereUniqueWithoutWorkoutTemplateInput[];
        createMany?: Prisma.WorkoutSessionCreateManyWorkoutTemplateInputEnvelope;
        set?:
            | Prisma.WorkoutSessionWhereUniqueInput
            | Prisma.WorkoutSessionWhereUniqueInput[];
        disconnect?:
            | Prisma.WorkoutSessionWhereUniqueInput
            | Prisma.WorkoutSessionWhereUniqueInput[];
        delete?:
            | Prisma.WorkoutSessionWhereUniqueInput
            | Prisma.WorkoutSessionWhereUniqueInput[];
        connect?:
            | Prisma.WorkoutSessionWhereUniqueInput
            | Prisma.WorkoutSessionWhereUniqueInput[];
        update?:
            | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutWorkoutTemplateInput
            | Prisma.WorkoutSessionUpdateWithWhereUniqueWithoutWorkoutTemplateInput[];
        updateMany?:
            | Prisma.WorkoutSessionUpdateManyWithWhereWithoutWorkoutTemplateInput
            | Prisma.WorkoutSessionUpdateManyWithWhereWithoutWorkoutTemplateInput[];
        deleteMany?:
            | Prisma.WorkoutSessionScalarWhereInput
            | Prisma.WorkoutSessionScalarWhereInput[];
    };

export type NullableDateTimeFieldUpdateOperationsInput = {
    set?: Date | string | null;
};

export type WorkoutSessionCreateNestedOneWithoutExercisesInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutExercisesInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutExercisesInput
    >;
    connectOrCreate?: Prisma.WorkoutSessionCreateOrConnectWithoutExercisesInput;
    connect?: Prisma.WorkoutSessionWhereUniqueInput;
};

export type WorkoutSessionUpdateOneRequiredWithoutExercisesNestedInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutExercisesInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutExercisesInput
    >;
    connectOrCreate?: Prisma.WorkoutSessionCreateOrConnectWithoutExercisesInput;
    upsert?: Prisma.WorkoutSessionUpsertWithoutExercisesInput;
    connect?: Prisma.WorkoutSessionWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.WorkoutSessionUpdateToOneWithWhereWithoutExercisesInput,
            Prisma.WorkoutSessionUpdateWithoutExercisesInput
        >,
        Prisma.WorkoutSessionUncheckedUpdateWithoutExercisesInput
    >;
};

export type WorkoutSessionCreateWithoutUserInput = {
    id?: string;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    workoutTemplate?: Prisma.WorkoutTemplateCreateNestedOneWithoutSessionsInput;
    exercises?: Prisma.WorkoutSessionExerciseCreateNestedManyWithoutSessionInput;
};

export type WorkoutSessionUncheckedCreateWithoutUserInput = {
    id?: string;
    workoutTemplateId?: string | null;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    exercises?: Prisma.WorkoutSessionExerciseUncheckedCreateNestedManyWithoutSessionInput;
};

export type WorkoutSessionCreateOrConnectWithoutUserInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutUserInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutUserInput
    >;
};

export type WorkoutSessionCreateManyUserInputEnvelope = {
    data:
        | Prisma.WorkoutSessionCreateManyUserInput
        | Prisma.WorkoutSessionCreateManyUserInput[];
    skipDuplicates?: boolean;
};

export type WorkoutSessionUpsertWithWhereUniqueWithoutUserInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.WorkoutSessionUpdateWithoutUserInput,
        Prisma.WorkoutSessionUncheckedUpdateWithoutUserInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutUserInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutUserInput
    >;
};

export type WorkoutSessionUpdateWithWhereUniqueWithoutUserInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateWithoutUserInput,
        Prisma.WorkoutSessionUncheckedUpdateWithoutUserInput
    >;
};

export type WorkoutSessionUpdateManyWithWhereWithoutUserInput = {
    where: Prisma.WorkoutSessionScalarWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateManyMutationInput,
        Prisma.WorkoutSessionUncheckedUpdateManyWithoutUserInput
    >;
};

export type WorkoutSessionScalarWhereInput = {
    AND?:
        | Prisma.WorkoutSessionScalarWhereInput
        | Prisma.WorkoutSessionScalarWhereInput[];
    OR?: Prisma.WorkoutSessionScalarWhereInput[];
    NOT?:
        | Prisma.WorkoutSessionScalarWhereInput
        | Prisma.WorkoutSessionScalarWhereInput[];
    id?: Prisma.StringFilter<'WorkoutSession'> | string;
    userId?: Prisma.StringFilter<'WorkoutSession'> | string;
    workoutTemplateId?:
        | Prisma.StringNullableFilter<'WorkoutSession'>
        | string
        | null;
    startedAt?: Prisma.DateTimeFilter<'WorkoutSession'> | Date | string;
    finishedAt?:
        | Prisma.DateTimeNullableFilter<'WorkoutSession'>
        | Date
        | string
        | null;
};

export type WorkoutSessionCreateWithoutWorkoutTemplateInput = {
    id?: string;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    user: Prisma.UserCreateNestedOneWithoutSessionsInput;
    exercises?: Prisma.WorkoutSessionExerciseCreateNestedManyWithoutSessionInput;
};

export type WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput = {
    id?: string;
    userId: string;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    exercises?: Prisma.WorkoutSessionExerciseUncheckedCreateNestedManyWithoutSessionInput;
};

export type WorkoutSessionCreateOrConnectWithoutWorkoutTemplateInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput
    >;
};

export type WorkoutSessionCreateManyWorkoutTemplateInputEnvelope = {
    data:
        | Prisma.WorkoutSessionCreateManyWorkoutTemplateInput
        | Prisma.WorkoutSessionCreateManyWorkoutTemplateInput[];
    skipDuplicates?: boolean;
};

export type WorkoutSessionUpsertWithWhereUniqueWithoutWorkoutTemplateInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.WorkoutSessionUpdateWithoutWorkoutTemplateInput,
        Prisma.WorkoutSessionUncheckedUpdateWithoutWorkoutTemplateInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutWorkoutTemplateInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutWorkoutTemplateInput
    >;
};

export type WorkoutSessionUpdateWithWhereUniqueWithoutWorkoutTemplateInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateWithoutWorkoutTemplateInput,
        Prisma.WorkoutSessionUncheckedUpdateWithoutWorkoutTemplateInput
    >;
};

export type WorkoutSessionUpdateManyWithWhereWithoutWorkoutTemplateInput = {
    where: Prisma.WorkoutSessionScalarWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateManyMutationInput,
        Prisma.WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateInput
    >;
};

export type WorkoutSessionCreateWithoutExercisesInput = {
    id?: string;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
    user: Prisma.UserCreateNestedOneWithoutSessionsInput;
    workoutTemplate?: Prisma.WorkoutTemplateCreateNestedOneWithoutSessionsInput;
};

export type WorkoutSessionUncheckedCreateWithoutExercisesInput = {
    id?: string;
    userId: string;
    workoutTemplateId?: string | null;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
};

export type WorkoutSessionCreateOrConnectWithoutExercisesInput = {
    where: Prisma.WorkoutSessionWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutExercisesInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutExercisesInput
    >;
};

export type WorkoutSessionUpsertWithoutExercisesInput = {
    update: Prisma.XOR<
        Prisma.WorkoutSessionUpdateWithoutExercisesInput,
        Prisma.WorkoutSessionUncheckedUpdateWithoutExercisesInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateWithoutExercisesInput,
        Prisma.WorkoutSessionUncheckedCreateWithoutExercisesInput
    >;
    where?: Prisma.WorkoutSessionWhereInput;
};

export type WorkoutSessionUpdateToOneWithWhereWithoutExercisesInput = {
    where?: Prisma.WorkoutSessionWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateWithoutExercisesInput,
        Prisma.WorkoutSessionUncheckedUpdateWithoutExercisesInput
    >;
};

export type WorkoutSessionUpdateWithoutExercisesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput;
    workoutTemplate?: Prisma.WorkoutTemplateUpdateOneWithoutSessionsNestedInput;
};

export type WorkoutSessionUncheckedUpdateWithoutExercisesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
};

export type WorkoutSessionCreateManyUserInput = {
    id?: string;
    workoutTemplateId?: string | null;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
};

export type WorkoutSessionUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    workoutTemplate?: Prisma.WorkoutTemplateUpdateOneWithoutSessionsNestedInput;
    exercises?: Prisma.WorkoutSessionExerciseUpdateManyWithoutSessionNestedInput;
};

export type WorkoutSessionUncheckedUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    exercises?: Prisma.WorkoutSessionExerciseUncheckedUpdateManyWithoutSessionNestedInput;
};

export type WorkoutSessionUncheckedUpdateManyWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    workoutTemplateId?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
};

export type WorkoutSessionCreateManyWorkoutTemplateInput = {
    id?: string;
    userId: string;
    startedAt?: Date | string;
    finishedAt?: Date | string | null;
};

export type WorkoutSessionUpdateWithoutWorkoutTemplateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput;
    exercises?: Prisma.WorkoutSessionExerciseUpdateManyWithoutSessionNestedInput;
};

export type WorkoutSessionUncheckedUpdateWithoutWorkoutTemplateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
    exercises?: Prisma.WorkoutSessionExerciseUncheckedUpdateManyWithoutSessionNestedInput;
};

export type WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    finishedAt?:
        | Prisma.NullableDateTimeFieldUpdateOperationsInput
        | Date
        | string
        | null;
};

/**
 * Count Type WorkoutSessionCountOutputType
 */

export type WorkoutSessionCountOutputType = {
    exercises: number;
};

export type WorkoutSessionCountOutputTypeSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    exercises?: boolean | WorkoutSessionCountOutputTypeCountExercisesArgs;
};

/**
 * WorkoutSessionCountOutputType without action
 */
export type WorkoutSessionCountOutputTypeDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionCountOutputType
     */
    select?: Prisma.WorkoutSessionCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * WorkoutSessionCountOutputType without action
 */
export type WorkoutSessionCountOutputTypeCountExercisesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.WorkoutSessionExerciseWhereInput;
};

export type WorkoutSessionSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        userId?: boolean;
        workoutTemplateId?: boolean;
        startedAt?: boolean;
        finishedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
        workoutTemplate?:
            | boolean
            | Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>;
        exercises?: boolean | Prisma.WorkoutSession$exercisesArgs<ExtArgs>;
        _count?:
            | boolean
            | Prisma.WorkoutSessionCountOutputTypeDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutSession']
>;

export type WorkoutSessionSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        userId?: boolean;
        workoutTemplateId?: boolean;
        startedAt?: boolean;
        finishedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
        workoutTemplate?:
            | boolean
            | Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutSession']
>;

export type WorkoutSessionSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        userId?: boolean;
        workoutTemplateId?: boolean;
        startedAt?: boolean;
        finishedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
        workoutTemplate?:
            | boolean
            | Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutSession']
>;

export type WorkoutSessionSelectScalar = {
    id?: boolean;
    userId?: boolean;
    workoutTemplateId?: boolean;
    startedAt?: boolean;
    finishedAt?: boolean;
};

export type WorkoutSessionOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    'id' | 'userId' | 'workoutTemplateId' | 'startedAt' | 'finishedAt',
    ExtArgs['result']['workoutSession']
>;
export type WorkoutSessionInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    workoutTemplate?:
        | boolean
        | Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>;
    exercises?: boolean | Prisma.WorkoutSession$exercisesArgs<ExtArgs>;
    _count?: boolean | Prisma.WorkoutSessionCountOutputTypeDefaultArgs<ExtArgs>;
};
export type WorkoutSessionIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    workoutTemplate?:
        | boolean
        | Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>;
};
export type WorkoutSessionIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    workoutTemplate?:
        | boolean
        | Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>;
};

export type $WorkoutSessionPayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: 'WorkoutSession';
    objects: {
        user: Prisma.$UserPayload<ExtArgs>;
        workoutTemplate: Prisma.$WorkoutTemplatePayload<ExtArgs> | null;
        exercises: Prisma.$WorkoutSessionExercisePayload<ExtArgs>[];
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            userId: string;
            workoutTemplateId: string | null;
            startedAt: Date;
            finishedAt: Date | null;
        },
        ExtArgs['result']['workoutSession']
    >;
    composites: {};
};

export type WorkoutSessionGetPayload<
    S extends boolean | null | undefined | WorkoutSessionDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WorkoutSessionPayload, S>;

export type WorkoutSessionCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<
    WorkoutSessionFindManyArgs,
    'select' | 'include' | 'distinct' | 'omit'
> & {
    select?: WorkoutSessionCountAggregateInputType | true;
};

export interface WorkoutSessionDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>['model']['WorkoutSession'];
        meta: { name: 'WorkoutSession' };
    };
    /**
     * Find zero or one WorkoutSession that matches the filter.
     * @param {WorkoutSessionFindUniqueArgs} args - Arguments to find a WorkoutSession
     * @example
     * // Get one WorkoutSession
     * const workoutSession = await prisma.workoutSession.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends WorkoutSessionFindUniqueArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'findUnique',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one WorkoutSession that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {WorkoutSessionFindUniqueOrThrowArgs} args - Arguments to find a WorkoutSession
     * @example
     * // Get one WorkoutSession
     * const workoutSession = await prisma.workoutSession.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends WorkoutSessionFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutSessionFindUniqueOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first WorkoutSession that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionFindFirstArgs} args - Arguments to find a WorkoutSession
     * @example
     * // Get one WorkoutSession
     * const workoutSession = await prisma.workoutSession.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends WorkoutSessionFindFirstArgs>(
        args?: Prisma.SelectSubset<T, WorkoutSessionFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'findFirst',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first WorkoutSession that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionFindFirstOrThrowArgs} args - Arguments to find a WorkoutSession
     * @example
     * // Get one WorkoutSession
     * const workoutSession = await prisma.workoutSession.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends WorkoutSessionFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionFindFirstOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'findFirstOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more WorkoutSessions that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all WorkoutSessions
     * const workoutSessions = await prisma.workoutSession.findMany()
     *
     * // Get first 10 WorkoutSessions
     * const workoutSessions = await prisma.workoutSession.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const workoutSessionWithIdOnly = await prisma.workoutSession.findMany({ select: { id: true } })
     *
     */
    findMany<T extends WorkoutSessionFindManyArgs>(
        args?: Prisma.SelectSubset<T, WorkoutSessionFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'findMany',
            GlobalOmitOptions
        >
    >;

    /**
     * Create a WorkoutSession.
     * @param {WorkoutSessionCreateArgs} args - Arguments to create a WorkoutSession.
     * @example
     * // Create one WorkoutSession
     * const WorkoutSession = await prisma.workoutSession.create({
     *   data: {
     *     // ... data to create a WorkoutSession
     *   }
     * })
     *
     */
    create<T extends WorkoutSessionCreateArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'create',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many WorkoutSessions.
     * @param {WorkoutSessionCreateManyArgs} args - Arguments to create many WorkoutSessions.
     * @example
     * // Create many WorkoutSessions
     * const workoutSession = await prisma.workoutSession.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends WorkoutSessionCreateManyArgs>(
        args?: Prisma.SelectSubset<T, WorkoutSessionCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many WorkoutSessions and returns the data saved in the database.
     * @param {WorkoutSessionCreateManyAndReturnArgs} args - Arguments to create many WorkoutSessions.
     * @example
     * // Create many WorkoutSessions
     * const workoutSession = await prisma.workoutSession.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many WorkoutSessions and only return the `id`
     * const workoutSessionWithIdOnly = await prisma.workoutSession.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends WorkoutSessionCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionCreateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'createManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a WorkoutSession.
     * @param {WorkoutSessionDeleteArgs} args - Arguments to delete one WorkoutSession.
     * @example
     * // Delete one WorkoutSession
     * const WorkoutSession = await prisma.workoutSession.delete({
     *   where: {
     *     // ... filter to delete one WorkoutSession
     *   }
     * })
     *
     */
    delete<T extends WorkoutSessionDeleteArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'delete',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one WorkoutSession.
     * @param {WorkoutSessionUpdateArgs} args - Arguments to update one WorkoutSession.
     * @example
     * // Update one WorkoutSession
     * const workoutSession = await prisma.workoutSession.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends WorkoutSessionUpdateArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'update',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more WorkoutSessions.
     * @param {WorkoutSessionDeleteManyArgs} args - Arguments to filter WorkoutSessions to delete.
     * @example
     * // Delete a few WorkoutSessions
     * const { count } = await prisma.workoutSession.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends WorkoutSessionDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, WorkoutSessionDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more WorkoutSessions.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many WorkoutSessions
     * const workoutSession = await prisma.workoutSession.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends WorkoutSessionUpdateManyArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more WorkoutSessions and returns the data updated in the database.
     * @param {WorkoutSessionUpdateManyAndReturnArgs} args - Arguments to update many WorkoutSessions.
     * @example
     * // Update many WorkoutSessions
     * const workoutSession = await prisma.workoutSession.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more WorkoutSessions and only return the `id`
     * const workoutSessionWithIdOnly = await prisma.workoutSession.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends WorkoutSessionUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutSessionUpdateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'updateManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one WorkoutSession.
     * @param {WorkoutSessionUpsertArgs} args - Arguments to update or create a WorkoutSession.
     * @example
     * // Update or create a WorkoutSession
     * const workoutSession = await prisma.workoutSession.upsert({
     *   create: {
     *     // ... data to create a WorkoutSession
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the WorkoutSession we want to update
     *   }
     * })
     */
    upsert<T extends WorkoutSessionUpsertArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionPayload<ExtArgs>,
            T,
            'upsert',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of WorkoutSessions.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionCountArgs} args - Arguments to filter WorkoutSessions to count.
     * @example
     * // Count the number of WorkoutSessions
     * const count = await prisma.workoutSession.count({
     *   where: {
     *     // ... the filter for the WorkoutSessions we want to count
     *   }
     * })
     **/
    count<T extends WorkoutSessionCountArgs>(
        args?: Prisma.Subset<T, WorkoutSessionCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<
                      T['select'],
                      WorkoutSessionCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a WorkoutSession.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends WorkoutSessionAggregateArgs>(
        args: Prisma.Subset<T, WorkoutSessionAggregateArgs>,
    ): Prisma.PrismaPromise<GetWorkoutSessionAggregateType<T>>;

    /**
     * Group by WorkoutSession.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends WorkoutSessionGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: WorkoutSessionGroupByArgs['orderBy'] }
            : { orderBy?: WorkoutSessionGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                'Field ',
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : 'take' extends Prisma.Keys<T>
                ? 'orderBy' extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : 'skip' extends Prisma.Keys<T>
                  ? 'orderBy' extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<
            T,
            WorkoutSessionGroupByArgs,
            OrderByArg
        > &
            InputErrors,
    ): {} extends InputErrors
        ? GetWorkoutSessionGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the WorkoutSession model
     */
    readonly fields: WorkoutSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkoutSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkoutSessionClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: 'PrismaPromise';
    user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__UserClient<
        | runtime.Types.Result.GetResult<
              Prisma.$UserPayload<ExtArgs>,
              T,
              'findUniqueOrThrow',
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    workoutTemplate<
        T extends Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs> = {},
    >(
        args?: Prisma.Subset<
            T,
            Prisma.WorkoutSession$workoutTemplateArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;
    exercises<T extends Prisma.WorkoutSession$exercisesArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutSession$exercisesArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
              T,
              'findMany',
              GlobalOmitOptions
          >
        | Null
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the WorkoutSession model
 */
export interface WorkoutSessionFieldRefs {
    readonly id: Prisma.FieldRef<'WorkoutSession', 'String'>;
    readonly userId: Prisma.FieldRef<'WorkoutSession', 'String'>;
    readonly workoutTemplateId: Prisma.FieldRef<'WorkoutSession', 'String'>;
    readonly startedAt: Prisma.FieldRef<'WorkoutSession', 'DateTime'>;
    readonly finishedAt: Prisma.FieldRef<'WorkoutSession', 'DateTime'>;
}

// Custom InputTypes
/**
 * WorkoutSession findUnique
 */
export type WorkoutSessionFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSession to fetch.
     */
    where: Prisma.WorkoutSessionWhereUniqueInput;
};

/**
 * WorkoutSession findUniqueOrThrow
 */
export type WorkoutSessionFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSession to fetch.
     */
    where: Prisma.WorkoutSessionWhereUniqueInput;
};

/**
 * WorkoutSession findFirst
 */
export type WorkoutSessionFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSession to fetch.
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessions to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionOrderByWithRelationInput
        | Prisma.WorkoutSessionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for WorkoutSessions.
     */
    cursor?: Prisma.WorkoutSessionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutSessions.
     */
    distinct?:
        | Prisma.WorkoutSessionScalarFieldEnum
        | Prisma.WorkoutSessionScalarFieldEnum[];
};

/**
 * WorkoutSession findFirstOrThrow
 */
export type WorkoutSessionFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSession to fetch.
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessions to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionOrderByWithRelationInput
        | Prisma.WorkoutSessionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for WorkoutSessions.
     */
    cursor?: Prisma.WorkoutSessionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutSessions.
     */
    distinct?:
        | Prisma.WorkoutSessionScalarFieldEnum
        | Prisma.WorkoutSessionScalarFieldEnum[];
};

/**
 * WorkoutSession findMany
 */
export type WorkoutSessionFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSessions to fetch.
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessions to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionOrderByWithRelationInput
        | Prisma.WorkoutSessionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing WorkoutSessions.
     */
    cursor?: Prisma.WorkoutSessionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutSessions.
     */
    distinct?:
        | Prisma.WorkoutSessionScalarFieldEnum
        | Prisma.WorkoutSessionScalarFieldEnum[];
};

/**
 * WorkoutSession create
 */
export type WorkoutSessionCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * The data needed to create a WorkoutSession.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionCreateInput,
        Prisma.WorkoutSessionUncheckedCreateInput
    >;
};

/**
 * WorkoutSession createMany
 */
export type WorkoutSessionCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many WorkoutSessions.
     */
    data:
        | Prisma.WorkoutSessionCreateManyInput
        | Prisma.WorkoutSessionCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * WorkoutSession createManyAndReturn
 */
export type WorkoutSessionCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * The data used to create many WorkoutSessions.
     */
    data:
        | Prisma.WorkoutSessionCreateManyInput
        | Prisma.WorkoutSessionCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * WorkoutSession update
 */
export type WorkoutSessionUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * The data needed to update a WorkoutSession.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateInput,
        Prisma.WorkoutSessionUncheckedUpdateInput
    >;
    /**
     * Choose, which WorkoutSession to update.
     */
    where: Prisma.WorkoutSessionWhereUniqueInput;
};

/**
 * WorkoutSession updateMany
 */
export type WorkoutSessionUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update WorkoutSessions.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateManyMutationInput,
        Prisma.WorkoutSessionUncheckedUpdateManyInput
    >;
    /**
     * Filter which WorkoutSessions to update
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * Limit how many WorkoutSessions to update.
     */
    limit?: number;
};

/**
 * WorkoutSession updateManyAndReturn
 */
export type WorkoutSessionUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * The data used to update WorkoutSessions.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionUpdateManyMutationInput,
        Prisma.WorkoutSessionUncheckedUpdateManyInput
    >;
    /**
     * Filter which WorkoutSessions to update
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * Limit how many WorkoutSessions to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * WorkoutSession upsert
 */
export type WorkoutSessionUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * The filter to search for the WorkoutSession to update in case it exists.
     */
    where: Prisma.WorkoutSessionWhereUniqueInput;
    /**
     * In case the WorkoutSession found by the `where` argument doesn't exist, create a new WorkoutSession with this data.
     */
    create: Prisma.XOR<
        Prisma.WorkoutSessionCreateInput,
        Prisma.WorkoutSessionUncheckedCreateInput
    >;
    /**
     * In case the WorkoutSession was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.WorkoutSessionUpdateInput,
        Prisma.WorkoutSessionUncheckedUpdateInput
    >;
};

/**
 * WorkoutSession delete
 */
export type WorkoutSessionDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    /**
     * Filter which WorkoutSession to delete.
     */
    where: Prisma.WorkoutSessionWhereUniqueInput;
};

/**
 * WorkoutSession deleteMany
 */
export type WorkoutSessionDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which WorkoutSessions to delete
     */
    where?: Prisma.WorkoutSessionWhereInput;
    /**
     * Limit how many WorkoutSessions to delete.
     */
    limit?: number;
};

/**
 * WorkoutSession.workoutTemplate
 */
export type WorkoutSession$workoutTemplateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    where?: Prisma.WorkoutTemplateWhereInput;
};

/**
 * WorkoutSession.exercises
 */
export type WorkoutSession$exercisesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    orderBy?:
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput[];
    cursor?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?:
        | Prisma.WorkoutSessionExerciseScalarFieldEnum
        | Prisma.WorkoutSessionExerciseScalarFieldEnum[];
};

/**
 * WorkoutSession without action
 */
export type WorkoutSessionDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
};
