/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WorkoutTemplate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model WorkoutTemplate
 *
 */
export type WorkoutTemplateModel =
    runtime.Types.Result.DefaultSelection<Prisma.$WorkoutTemplatePayload>;

export type AggregateWorkoutTemplate = {
    _count: WorkoutTemplateCountAggregateOutputType | null;
    _min: WorkoutTemplateMinAggregateOutputType | null;
    _max: WorkoutTemplateMaxAggregateOutputType | null;
};

export type WorkoutTemplateMinAggregateOutputType = {
    id: string | null;
    userId: string | null;
    name: string | null;
    description: string | null;
};

export type WorkoutTemplateMaxAggregateOutputType = {
    id: string | null;
    userId: string | null;
    name: string | null;
    description: string | null;
};

export type WorkoutTemplateCountAggregateOutputType = {
    id: number;
    userId: number;
    name: number;
    description: number;
    _all: number;
};

export type WorkoutTemplateMinAggregateInputType = {
    id?: true;
    userId?: true;
    name?: true;
    description?: true;
};

export type WorkoutTemplateMaxAggregateInputType = {
    id?: true;
    userId?: true;
    name?: true;
    description?: true;
};

export type WorkoutTemplateCountAggregateInputType = {
    id?: true;
    userId?: true;
    name?: true;
    description?: true;
    _all?: true;
};

export type WorkoutTemplateAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which WorkoutTemplate to aggregate.
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutTemplates to fetch.
     */
    orderBy?:
        | Prisma.WorkoutTemplateOrderByWithRelationInput
        | Prisma.WorkoutTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.WorkoutTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned WorkoutTemplates
     **/
    _count?: true | WorkoutTemplateCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: WorkoutTemplateMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: WorkoutTemplateMaxAggregateInputType;
};

export type GetWorkoutTemplateAggregateType<
    T extends WorkoutTemplateAggregateArgs,
> = {
    [P in keyof T & keyof AggregateWorkoutTemplate]: P extends
        | '_count'
        | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateWorkoutTemplate[P]>
        : Prisma.GetScalarType<T[P], AggregateWorkoutTemplate[P]>;
};

export type WorkoutTemplateGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.WorkoutTemplateWhereInput;
    orderBy?:
        | Prisma.WorkoutTemplateOrderByWithAggregationInput
        | Prisma.WorkoutTemplateOrderByWithAggregationInput[];
    by:
        | Prisma.WorkoutTemplateScalarFieldEnum[]
        | Prisma.WorkoutTemplateScalarFieldEnum;
    having?: Prisma.WorkoutTemplateScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: WorkoutTemplateCountAggregateInputType | true;
    _min?: WorkoutTemplateMinAggregateInputType;
    _max?: WorkoutTemplateMaxAggregateInputType;
};

export type WorkoutTemplateGroupByOutputType = {
    id: string;
    userId: string | null;
    name: string;
    description: string | null;
    _count: WorkoutTemplateCountAggregateOutputType | null;
    _min: WorkoutTemplateMinAggregateOutputType | null;
    _max: WorkoutTemplateMaxAggregateOutputType | null;
};

export type GetWorkoutTemplateGroupByPayload<
    T extends WorkoutTemplateGroupByArgs,
> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<WorkoutTemplateGroupByOutputType, T['by']> & {
            [P in keyof T &
                keyof WorkoutTemplateGroupByOutputType]: P extends '_count'
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<
                          T[P],
                          WorkoutTemplateGroupByOutputType[P]
                      >
                : Prisma.GetScalarType<
                      T[P],
                      WorkoutTemplateGroupByOutputType[P]
                  >;
        }
    >
>;

export type WorkoutTemplateWhereInput = {
    AND?: Prisma.WorkoutTemplateWhereInput | Prisma.WorkoutTemplateWhereInput[];
    OR?: Prisma.WorkoutTemplateWhereInput[];
    NOT?: Prisma.WorkoutTemplateWhereInput | Prisma.WorkoutTemplateWhereInput[];
    id?: Prisma.StringFilter<'WorkoutTemplate'> | string;
    userId?: Prisma.StringNullableFilter<'WorkoutTemplate'> | string | null;
    name?: Prisma.StringFilter<'WorkoutTemplate'> | string;
    description?:
        | Prisma.StringNullableFilter<'WorkoutTemplate'>
        | string
        | null;
    user?: Prisma.XOR<
        Prisma.UserNullableScalarRelationFilter,
        Prisma.UserWhereInput
    > | null;
    exercises?: Prisma.WorkoutTemplateExerciseListRelationFilter;
    sessions?: Prisma.WorkoutSessionListRelationFilter;
    routines?: Prisma.RoutineTemplateListRelationFilter;
};

export type WorkoutTemplateOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrderInput | Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrderInput | Prisma.SortOrder;
    user?: Prisma.UserOrderByWithRelationInput;
    exercises?: Prisma.WorkoutTemplateExerciseOrderByRelationAggregateInput;
    sessions?: Prisma.WorkoutSessionOrderByRelationAggregateInput;
    routines?: Prisma.RoutineTemplateOrderByRelationAggregateInput;
};

export type WorkoutTemplateWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?:
            | Prisma.WorkoutTemplateWhereInput
            | Prisma.WorkoutTemplateWhereInput[];
        OR?: Prisma.WorkoutTemplateWhereInput[];
        NOT?:
            | Prisma.WorkoutTemplateWhereInput
            | Prisma.WorkoutTemplateWhereInput[];
        userId?: Prisma.StringNullableFilter<'WorkoutTemplate'> | string | null;
        name?: Prisma.StringFilter<'WorkoutTemplate'> | string;
        description?:
            | Prisma.StringNullableFilter<'WorkoutTemplate'>
            | string
            | null;
        user?: Prisma.XOR<
            Prisma.UserNullableScalarRelationFilter,
            Prisma.UserWhereInput
        > | null;
        exercises?: Prisma.WorkoutTemplateExerciseListRelationFilter;
        sessions?: Prisma.WorkoutSessionListRelationFilter;
        routines?: Prisma.RoutineTemplateListRelationFilter;
    },
    'id'
>;

export type WorkoutTemplateOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrderInput | Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrderInput | Prisma.SortOrder;
    _count?: Prisma.WorkoutTemplateCountOrderByAggregateInput;
    _max?: Prisma.WorkoutTemplateMaxOrderByAggregateInput;
    _min?: Prisma.WorkoutTemplateMinOrderByAggregateInput;
};

export type WorkoutTemplateScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.WorkoutTemplateScalarWhereWithAggregatesInput
        | Prisma.WorkoutTemplateScalarWhereWithAggregatesInput[];
    OR?: Prisma.WorkoutTemplateScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.WorkoutTemplateScalarWhereWithAggregatesInput
        | Prisma.WorkoutTemplateScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<'WorkoutTemplate'> | string;
    userId?:
        | Prisma.StringNullableWithAggregatesFilter<'WorkoutTemplate'>
        | string
        | null;
    name?: Prisma.StringWithAggregatesFilter<'WorkoutTemplate'> | string;
    description?:
        | Prisma.StringNullableWithAggregatesFilter<'WorkoutTemplate'>
        | string
        | null;
};

export type WorkoutTemplateCreateInput = {
    id?: string;
    name: string;
    description?: string | null;
    user?: Prisma.UserCreateNestedOneWithoutTemplatesInput;
    exercises?: Prisma.WorkoutTemplateExerciseCreateNestedManyWithoutWorkoutTemplateInput;
    sessions?: Prisma.WorkoutSessionCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateUncheckedCreateInput = {
    id?: string;
    userId?: string | null;
    name: string;
    description?: string | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    sessions?: Prisma.WorkoutSessionUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    user?: Prisma.UserUpdateOneWithoutTemplatesNestedInput;
    exercises?: Prisma.WorkoutTemplateExerciseUpdateManyWithoutWorkoutTemplateNestedInput;
    sessions?: Prisma.WorkoutSessionUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    sessions?: Prisma.WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateCreateManyInput = {
    id?: string;
    userId?: string | null;
    name: string;
    description?: string | null;
};

export type WorkoutTemplateUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
};

export type WorkoutTemplateUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
};

export type WorkoutTemplateListRelationFilter = {
    every?: Prisma.WorkoutTemplateWhereInput;
    some?: Prisma.WorkoutTemplateWhereInput;
    none?: Prisma.WorkoutTemplateWhereInput;
};

export type WorkoutTemplateOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type WorkoutTemplateCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
};

export type WorkoutTemplateMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
};

export type WorkoutTemplateMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
};

export type WorkoutTemplateScalarRelationFilter = {
    is?: Prisma.WorkoutTemplateWhereInput;
    isNot?: Prisma.WorkoutTemplateWhereInput;
};

export type WorkoutTemplateNullableScalarRelationFilter = {
    is?: Prisma.WorkoutTemplateWhereInput | null;
    isNot?: Prisma.WorkoutTemplateWhereInput | null;
};

export type WorkoutTemplateCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutTemplateCreateWithoutUserInput,
              Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutTemplateCreateWithoutUserInput[]
        | Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.WorkoutTemplateCreateManyUserInputEnvelope;
    connect?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
};

export type WorkoutTemplateUncheckedCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutTemplateCreateWithoutUserInput,
              Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutTemplateCreateWithoutUserInput[]
        | Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.WorkoutTemplateCreateManyUserInputEnvelope;
    connect?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
};

export type WorkoutTemplateUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutTemplateCreateWithoutUserInput,
              Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutTemplateCreateWithoutUserInput[]
        | Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.WorkoutTemplateUpsertWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutTemplateUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.WorkoutTemplateCreateManyUserInputEnvelope;
    set?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    update?:
        | Prisma.WorkoutTemplateUpdateWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutTemplateUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.WorkoutTemplateUpdateManyWithWhereWithoutUserInput
        | Prisma.WorkoutTemplateUpdateManyWithWhereWithoutUserInput[];
    deleteMany?:
        | Prisma.WorkoutTemplateScalarWhereInput
        | Prisma.WorkoutTemplateScalarWhereInput[];
};

export type WorkoutTemplateUncheckedUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutTemplateCreateWithoutUserInput,
              Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput
          >
        | Prisma.WorkoutTemplateCreateWithoutUserInput[]
        | Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput
        | Prisma.WorkoutTemplateCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.WorkoutTemplateUpsertWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutTemplateUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.WorkoutTemplateCreateManyUserInputEnvelope;
    set?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutTemplateWhereUniqueInput
        | Prisma.WorkoutTemplateWhereUniqueInput[];
    update?:
        | Prisma.WorkoutTemplateUpdateWithWhereUniqueWithoutUserInput
        | Prisma.WorkoutTemplateUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.WorkoutTemplateUpdateManyWithWhereWithoutUserInput
        | Prisma.WorkoutTemplateUpdateManyWithWhereWithoutUserInput[];
    deleteMany?:
        | Prisma.WorkoutTemplateScalarWhereInput
        | Prisma.WorkoutTemplateScalarWhereInput[];
};

export type WorkoutTemplateCreateNestedOneWithoutExercisesInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutExercisesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutExercisesInput
    >;
    connectOrCreate?: Prisma.WorkoutTemplateCreateOrConnectWithoutExercisesInput;
    connect?: Prisma.WorkoutTemplateWhereUniqueInput;
};

export type WorkoutTemplateUpdateOneRequiredWithoutExercisesNestedInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutExercisesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutExercisesInput
    >;
    connectOrCreate?: Prisma.WorkoutTemplateCreateOrConnectWithoutExercisesInput;
    upsert?: Prisma.WorkoutTemplateUpsertWithoutExercisesInput;
    connect?: Prisma.WorkoutTemplateWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.WorkoutTemplateUpdateToOneWithWhereWithoutExercisesInput,
            Prisma.WorkoutTemplateUpdateWithoutExercisesInput
        >,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutExercisesInput
    >;
};

export type WorkoutTemplateCreateNestedOneWithoutSessionsInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutSessionsInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutSessionsInput
    >;
    connectOrCreate?: Prisma.WorkoutTemplateCreateOrConnectWithoutSessionsInput;
    connect?: Prisma.WorkoutTemplateWhereUniqueInput;
};

export type WorkoutTemplateUpdateOneWithoutSessionsNestedInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutSessionsInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutSessionsInput
    >;
    connectOrCreate?: Prisma.WorkoutTemplateCreateOrConnectWithoutSessionsInput;
    upsert?: Prisma.WorkoutTemplateUpsertWithoutSessionsInput;
    disconnect?: Prisma.WorkoutTemplateWhereInput | boolean;
    delete?: Prisma.WorkoutTemplateWhereInput | boolean;
    connect?: Prisma.WorkoutTemplateWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.WorkoutTemplateUpdateToOneWithWhereWithoutSessionsInput,
            Prisma.WorkoutTemplateUpdateWithoutSessionsInput
        >,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutSessionsInput
    >;
};

export type WorkoutTemplateCreateNestedOneWithoutRoutinesInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutRoutinesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutRoutinesInput
    >;
    connectOrCreate?: Prisma.WorkoutTemplateCreateOrConnectWithoutRoutinesInput;
    connect?: Prisma.WorkoutTemplateWhereUniqueInput;
};

export type WorkoutTemplateUpdateOneRequiredWithoutRoutinesNestedInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutRoutinesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutRoutinesInput
    >;
    connectOrCreate?: Prisma.WorkoutTemplateCreateOrConnectWithoutRoutinesInput;
    upsert?: Prisma.WorkoutTemplateUpsertWithoutRoutinesInput;
    connect?: Prisma.WorkoutTemplateWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.WorkoutTemplateUpdateToOneWithWhereWithoutRoutinesInput,
            Prisma.WorkoutTemplateUpdateWithoutRoutinesInput
        >,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutRoutinesInput
    >;
};

export type WorkoutTemplateCreateWithoutUserInput = {
    id?: string;
    name: string;
    description?: string | null;
    exercises?: Prisma.WorkoutTemplateExerciseCreateNestedManyWithoutWorkoutTemplateInput;
    sessions?: Prisma.WorkoutSessionCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateUncheckedCreateWithoutUserInput = {
    id?: string;
    name: string;
    description?: string | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    sessions?: Prisma.WorkoutSessionUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateCreateOrConnectWithoutUserInput = {
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutUserInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput
    >;
};

export type WorkoutTemplateCreateManyUserInputEnvelope = {
    data:
        | Prisma.WorkoutTemplateCreateManyUserInput
        | Prisma.WorkoutTemplateCreateManyUserInput[];
    skipDuplicates?: boolean;
};

export type WorkoutTemplateUpsertWithWhereUniqueWithoutUserInput = {
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutUserInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutUserInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutUserInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutUserInput
    >;
};

export type WorkoutTemplateUpdateWithWhereUniqueWithoutUserInput = {
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutUserInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutUserInput
    >;
};

export type WorkoutTemplateUpdateManyWithWhereWithoutUserInput = {
    where: Prisma.WorkoutTemplateScalarWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateManyMutationInput,
        Prisma.WorkoutTemplateUncheckedUpdateManyWithoutUserInput
    >;
};

export type WorkoutTemplateScalarWhereInput = {
    AND?:
        | Prisma.WorkoutTemplateScalarWhereInput
        | Prisma.WorkoutTemplateScalarWhereInput[];
    OR?: Prisma.WorkoutTemplateScalarWhereInput[];
    NOT?:
        | Prisma.WorkoutTemplateScalarWhereInput
        | Prisma.WorkoutTemplateScalarWhereInput[];
    id?: Prisma.StringFilter<'WorkoutTemplate'> | string;
    userId?: Prisma.StringNullableFilter<'WorkoutTemplate'> | string | null;
    name?: Prisma.StringFilter<'WorkoutTemplate'> | string;
    description?:
        | Prisma.StringNullableFilter<'WorkoutTemplate'>
        | string
        | null;
};

export type WorkoutTemplateCreateWithoutExercisesInput = {
    id?: string;
    name: string;
    description?: string | null;
    user?: Prisma.UserCreateNestedOneWithoutTemplatesInput;
    sessions?: Prisma.WorkoutSessionCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateUncheckedCreateWithoutExercisesInput = {
    id?: string;
    userId?: string | null;
    name: string;
    description?: string | null;
    sessions?: Prisma.WorkoutSessionUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateCreateOrConnectWithoutExercisesInput = {
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutExercisesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutExercisesInput
    >;
};

export type WorkoutTemplateUpsertWithoutExercisesInput = {
    update: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutExercisesInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutExercisesInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutExercisesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutExercisesInput
    >;
    where?: Prisma.WorkoutTemplateWhereInput;
};

export type WorkoutTemplateUpdateToOneWithWhereWithoutExercisesInput = {
    where?: Prisma.WorkoutTemplateWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutExercisesInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutExercisesInput
    >;
};

export type WorkoutTemplateUpdateWithoutExercisesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    user?: Prisma.UserUpdateOneWithoutTemplatesNestedInput;
    sessions?: Prisma.WorkoutSessionUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateUncheckedUpdateWithoutExercisesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    sessions?: Prisma.WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateCreateWithoutSessionsInput = {
    id?: string;
    name: string;
    description?: string | null;
    user?: Prisma.UserCreateNestedOneWithoutTemplatesInput;
    exercises?: Prisma.WorkoutTemplateExerciseCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateUncheckedCreateWithoutSessionsInput = {
    id?: string;
    userId?: string | null;
    name: string;
    description?: string | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    routines?: Prisma.RoutineTemplateUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateCreateOrConnectWithoutSessionsInput = {
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutSessionsInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutSessionsInput
    >;
};

export type WorkoutTemplateUpsertWithoutSessionsInput = {
    update: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutSessionsInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutSessionsInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutSessionsInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutSessionsInput
    >;
    where?: Prisma.WorkoutTemplateWhereInput;
};

export type WorkoutTemplateUpdateToOneWithWhereWithoutSessionsInput = {
    where?: Prisma.WorkoutTemplateWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutSessionsInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutSessionsInput
    >;
};

export type WorkoutTemplateUpdateWithoutSessionsInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    user?: Prisma.UserUpdateOneWithoutTemplatesNestedInput;
    exercises?: Prisma.WorkoutTemplateExerciseUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateUncheckedUpdateWithoutSessionsInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateCreateWithoutRoutinesInput = {
    id?: string;
    name: string;
    description?: string | null;
    user?: Prisma.UserCreateNestedOneWithoutTemplatesInput;
    exercises?: Prisma.WorkoutTemplateExerciseCreateNestedManyWithoutWorkoutTemplateInput;
    sessions?: Prisma.WorkoutSessionCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateUncheckedCreateWithoutRoutinesInput = {
    id?: string;
    userId?: string | null;
    name: string;
    description?: string | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
    sessions?: Prisma.WorkoutSessionUncheckedCreateNestedManyWithoutWorkoutTemplateInput;
};

export type WorkoutTemplateCreateOrConnectWithoutRoutinesInput = {
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutRoutinesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutRoutinesInput
    >;
};

export type WorkoutTemplateUpsertWithoutRoutinesInput = {
    update: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutRoutinesInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutRoutinesInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateWithoutRoutinesInput,
        Prisma.WorkoutTemplateUncheckedCreateWithoutRoutinesInput
    >;
    where?: Prisma.WorkoutTemplateWhereInput;
};

export type WorkoutTemplateUpdateToOneWithWhereWithoutRoutinesInput = {
    where?: Prisma.WorkoutTemplateWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateWithoutRoutinesInput,
        Prisma.WorkoutTemplateUncheckedUpdateWithoutRoutinesInput
    >;
};

export type WorkoutTemplateUpdateWithoutRoutinesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    user?: Prisma.UserUpdateOneWithoutTemplatesNestedInput;
    exercises?: Prisma.WorkoutTemplateExerciseUpdateManyWithoutWorkoutTemplateNestedInput;
    sessions?: Prisma.WorkoutSessionUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateUncheckedUpdateWithoutRoutinesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    sessions?: Prisma.WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateCreateManyUserInput = {
    id?: string;
    name: string;
    description?: string | null;
};

export type WorkoutTemplateUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    exercises?: Prisma.WorkoutTemplateExerciseUpdateManyWithoutWorkoutTemplateNestedInput;
    sessions?: Prisma.WorkoutSessionUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateUncheckedUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    exercises?: Prisma.WorkoutTemplateExerciseUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    sessions?: Prisma.WorkoutSessionUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
    routines?: Prisma.RoutineTemplateUncheckedUpdateManyWithoutWorkoutTemplateNestedInput;
};

export type WorkoutTemplateUncheckedUpdateManyWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
};

/**
 * Count Type WorkoutTemplateCountOutputType
 */

export type WorkoutTemplateCountOutputType = {
    exercises: number;
    sessions: number;
    routines: number;
};

export type WorkoutTemplateCountOutputTypeSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    exercises?: boolean | WorkoutTemplateCountOutputTypeCountExercisesArgs;
    sessions?: boolean | WorkoutTemplateCountOutputTypeCountSessionsArgs;
    routines?: boolean | WorkoutTemplateCountOutputTypeCountRoutinesArgs;
};

/**
 * WorkoutTemplateCountOutputType without action
 */
export type WorkoutTemplateCountOutputTypeDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplateCountOutputType
     */
    select?: Prisma.WorkoutTemplateCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * WorkoutTemplateCountOutputType without action
 */
export type WorkoutTemplateCountOutputTypeCountExercisesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.WorkoutTemplateExerciseWhereInput;
};

/**
 * WorkoutTemplateCountOutputType without action
 */
export type WorkoutTemplateCountOutputTypeCountSessionsArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.WorkoutSessionWhereInput;
};

/**
 * WorkoutTemplateCountOutputType without action
 */
export type WorkoutTemplateCountOutputTypeCountRoutinesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.RoutineTemplateWhereInput;
};

export type WorkoutTemplateSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        userId?: boolean;
        name?: boolean;
        description?: boolean;
        user?: boolean | Prisma.WorkoutTemplate$userArgs<ExtArgs>;
        exercises?: boolean | Prisma.WorkoutTemplate$exercisesArgs<ExtArgs>;
        sessions?: boolean | Prisma.WorkoutTemplate$sessionsArgs<ExtArgs>;
        routines?: boolean | Prisma.WorkoutTemplate$routinesArgs<ExtArgs>;
        _count?:
            | boolean
            | Prisma.WorkoutTemplateCountOutputTypeDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutTemplate']
>;

export type WorkoutTemplateSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        userId?: boolean;
        name?: boolean;
        description?: boolean;
        user?: boolean | Prisma.WorkoutTemplate$userArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutTemplate']
>;

export type WorkoutTemplateSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        userId?: boolean;
        name?: boolean;
        description?: boolean;
        user?: boolean | Prisma.WorkoutTemplate$userArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutTemplate']
>;

export type WorkoutTemplateSelectScalar = {
    id?: boolean;
    userId?: boolean;
    name?: boolean;
    description?: boolean;
};

export type WorkoutTemplateOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    'id' | 'userId' | 'name' | 'description',
    ExtArgs['result']['workoutTemplate']
>;
export type WorkoutTemplateInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.WorkoutTemplate$userArgs<ExtArgs>;
    exercises?: boolean | Prisma.WorkoutTemplate$exercisesArgs<ExtArgs>;
    sessions?: boolean | Prisma.WorkoutTemplate$sessionsArgs<ExtArgs>;
    routines?: boolean | Prisma.WorkoutTemplate$routinesArgs<ExtArgs>;
    _count?:
        | boolean
        | Prisma.WorkoutTemplateCountOutputTypeDefaultArgs<ExtArgs>;
};
export type WorkoutTemplateIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.WorkoutTemplate$userArgs<ExtArgs>;
};
export type WorkoutTemplateIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.WorkoutTemplate$userArgs<ExtArgs>;
};

export type $WorkoutTemplatePayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: 'WorkoutTemplate';
    objects: {
        user: Prisma.$UserPayload<ExtArgs> | null;
        exercises: Prisma.$WorkoutTemplateExercisePayload<ExtArgs>[];
        sessions: Prisma.$WorkoutSessionPayload<ExtArgs>[];
        routines: Prisma.$RoutineTemplatePayload<ExtArgs>[];
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            userId: string | null;
            name: string;
            description: string | null;
        },
        ExtArgs['result']['workoutTemplate']
    >;
    composites: {};
};

export type WorkoutTemplateGetPayload<
    S extends boolean | null | undefined | WorkoutTemplateDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WorkoutTemplatePayload, S>;

export type WorkoutTemplateCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<
    WorkoutTemplateFindManyArgs,
    'select' | 'include' | 'distinct' | 'omit'
> & {
    select?: WorkoutTemplateCountAggregateInputType | true;
};

export interface WorkoutTemplateDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>['model']['WorkoutTemplate'];
        meta: { name: 'WorkoutTemplate' };
    };
    /**
     * Find zero or one WorkoutTemplate that matches the filter.
     * @param {WorkoutTemplateFindUniqueArgs} args - Arguments to find a WorkoutTemplate
     * @example
     * // Get one WorkoutTemplate
     * const workoutTemplate = await prisma.workoutTemplate.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends WorkoutTemplateFindUniqueArgs>(
        args: Prisma.SelectSubset<T, WorkoutTemplateFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'findUnique',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one WorkoutTemplate that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {WorkoutTemplateFindUniqueOrThrowArgs} args - Arguments to find a WorkoutTemplate
     * @example
     * // Get one WorkoutTemplate
     * const workoutTemplate = await prisma.workoutTemplate.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends WorkoutTemplateFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutTemplateFindUniqueOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first WorkoutTemplate that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateFindFirstArgs} args - Arguments to find a WorkoutTemplate
     * @example
     * // Get one WorkoutTemplate
     * const workoutTemplate = await prisma.workoutTemplate.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends WorkoutTemplateFindFirstArgs>(
        args?: Prisma.SelectSubset<T, WorkoutTemplateFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'findFirst',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first WorkoutTemplate that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateFindFirstOrThrowArgs} args - Arguments to find a WorkoutTemplate
     * @example
     * // Get one WorkoutTemplate
     * const workoutTemplate = await prisma.workoutTemplate.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends WorkoutTemplateFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutTemplateFindFirstOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'findFirstOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more WorkoutTemplates that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all WorkoutTemplates
     * const workoutTemplates = await prisma.workoutTemplate.findMany()
     *
     * // Get first 10 WorkoutTemplates
     * const workoutTemplates = await prisma.workoutTemplate.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const workoutTemplateWithIdOnly = await prisma.workoutTemplate.findMany({ select: { id: true } })
     *
     */
    findMany<T extends WorkoutTemplateFindManyArgs>(
        args?: Prisma.SelectSubset<T, WorkoutTemplateFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'findMany',
            GlobalOmitOptions
        >
    >;

    /**
     * Create a WorkoutTemplate.
     * @param {WorkoutTemplateCreateArgs} args - Arguments to create a WorkoutTemplate.
     * @example
     * // Create one WorkoutTemplate
     * const WorkoutTemplate = await prisma.workoutTemplate.create({
     *   data: {
     *     // ... data to create a WorkoutTemplate
     *   }
     * })
     *
     */
    create<T extends WorkoutTemplateCreateArgs>(
        args: Prisma.SelectSubset<T, WorkoutTemplateCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'create',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many WorkoutTemplates.
     * @param {WorkoutTemplateCreateManyArgs} args - Arguments to create many WorkoutTemplates.
     * @example
     * // Create many WorkoutTemplates
     * const workoutTemplate = await prisma.workoutTemplate.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends WorkoutTemplateCreateManyArgs>(
        args?: Prisma.SelectSubset<T, WorkoutTemplateCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many WorkoutTemplates and returns the data saved in the database.
     * @param {WorkoutTemplateCreateManyAndReturnArgs} args - Arguments to create many WorkoutTemplates.
     * @example
     * // Create many WorkoutTemplates
     * const workoutTemplate = await prisma.workoutTemplate.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many WorkoutTemplates and only return the `id`
     * const workoutTemplateWithIdOnly = await prisma.workoutTemplate.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends WorkoutTemplateCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutTemplateCreateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'createManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a WorkoutTemplate.
     * @param {WorkoutTemplateDeleteArgs} args - Arguments to delete one WorkoutTemplate.
     * @example
     * // Delete one WorkoutTemplate
     * const WorkoutTemplate = await prisma.workoutTemplate.delete({
     *   where: {
     *     // ... filter to delete one WorkoutTemplate
     *   }
     * })
     *
     */
    delete<T extends WorkoutTemplateDeleteArgs>(
        args: Prisma.SelectSubset<T, WorkoutTemplateDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'delete',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one WorkoutTemplate.
     * @param {WorkoutTemplateUpdateArgs} args - Arguments to update one WorkoutTemplate.
     * @example
     * // Update one WorkoutTemplate
     * const workoutTemplate = await prisma.workoutTemplate.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends WorkoutTemplateUpdateArgs>(
        args: Prisma.SelectSubset<T, WorkoutTemplateUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'update',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more WorkoutTemplates.
     * @param {WorkoutTemplateDeleteManyArgs} args - Arguments to filter WorkoutTemplates to delete.
     * @example
     * // Delete a few WorkoutTemplates
     * const { count } = await prisma.workoutTemplate.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends WorkoutTemplateDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, WorkoutTemplateDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more WorkoutTemplates.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many WorkoutTemplates
     * const workoutTemplate = await prisma.workoutTemplate.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends WorkoutTemplateUpdateManyArgs>(
        args: Prisma.SelectSubset<T, WorkoutTemplateUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more WorkoutTemplates and returns the data updated in the database.
     * @param {WorkoutTemplateUpdateManyAndReturnArgs} args - Arguments to update many WorkoutTemplates.
     * @example
     * // Update many WorkoutTemplates
     * const workoutTemplate = await prisma.workoutTemplate.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more WorkoutTemplates and only return the `id`
     * const workoutTemplateWithIdOnly = await prisma.workoutTemplate.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends WorkoutTemplateUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutTemplateUpdateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'updateManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one WorkoutTemplate.
     * @param {WorkoutTemplateUpsertArgs} args - Arguments to update or create a WorkoutTemplate.
     * @example
     * // Update or create a WorkoutTemplate
     * const workoutTemplate = await prisma.workoutTemplate.upsert({
     *   create: {
     *     // ... data to create a WorkoutTemplate
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the WorkoutTemplate we want to update
     *   }
     * })
     */
    upsert<T extends WorkoutTemplateUpsertArgs>(
        args: Prisma.SelectSubset<T, WorkoutTemplateUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutTemplateClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutTemplatePayload<ExtArgs>,
            T,
            'upsert',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of WorkoutTemplates.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateCountArgs} args - Arguments to filter WorkoutTemplates to count.
     * @example
     * // Count the number of WorkoutTemplates
     * const count = await prisma.workoutTemplate.count({
     *   where: {
     *     // ... the filter for the WorkoutTemplates we want to count
     *   }
     * })
     **/
    count<T extends WorkoutTemplateCountArgs>(
        args?: Prisma.Subset<T, WorkoutTemplateCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<
                      T['select'],
                      WorkoutTemplateCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a WorkoutTemplate.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends WorkoutTemplateAggregateArgs>(
        args: Prisma.Subset<T, WorkoutTemplateAggregateArgs>,
    ): Prisma.PrismaPromise<GetWorkoutTemplateAggregateType<T>>;

    /**
     * Group by WorkoutTemplate.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutTemplateGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends WorkoutTemplateGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: WorkoutTemplateGroupByArgs['orderBy'] }
            : { orderBy?: WorkoutTemplateGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                'Field ',
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : 'take' extends Prisma.Keys<T>
                ? 'orderBy' extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : 'skip' extends Prisma.Keys<T>
                  ? 'orderBy' extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<
            T,
            WorkoutTemplateGroupByArgs,
            OrderByArg
        > &
            InputErrors,
    ): {} extends InputErrors
        ? GetWorkoutTemplateGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the WorkoutTemplate model
     */
    readonly fields: WorkoutTemplateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkoutTemplate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkoutTemplateClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: 'PrismaPromise';
    user<T extends Prisma.WorkoutTemplate$userArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutTemplate$userArgs<ExtArgs>>,
    ): Prisma.Prisma__UserClient<
        runtime.Types.Result.GetResult<
            Prisma.$UserPayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;
    exercises<T extends Prisma.WorkoutTemplate$exercisesArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutTemplate$exercisesArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$WorkoutTemplateExercisePayload<ExtArgs>,
              T,
              'findMany',
              GlobalOmitOptions
          >
        | Null
    >;
    sessions<T extends Prisma.WorkoutTemplate$sessionsArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutTemplate$sessionsArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$WorkoutSessionPayload<ExtArgs>,
              T,
              'findMany',
              GlobalOmitOptions
          >
        | Null
    >;
    routines<T extends Prisma.WorkoutTemplate$routinesArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutTemplate$routinesArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$RoutineTemplatePayload<ExtArgs>,
              T,
              'findMany',
              GlobalOmitOptions
          >
        | Null
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the WorkoutTemplate model
 */
export interface WorkoutTemplateFieldRefs {
    readonly id: Prisma.FieldRef<'WorkoutTemplate', 'String'>;
    readonly userId: Prisma.FieldRef<'WorkoutTemplate', 'String'>;
    readonly name: Prisma.FieldRef<'WorkoutTemplate', 'String'>;
    readonly description: Prisma.FieldRef<'WorkoutTemplate', 'String'>;
}

// Custom InputTypes
/**
 * WorkoutTemplate findUnique
 */
export type WorkoutTemplateFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutTemplate to fetch.
     */
    where: Prisma.WorkoutTemplateWhereUniqueInput;
};

/**
 * WorkoutTemplate findUniqueOrThrow
 */
export type WorkoutTemplateFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutTemplate to fetch.
     */
    where: Prisma.WorkoutTemplateWhereUniqueInput;
};

/**
 * WorkoutTemplate findFirst
 */
export type WorkoutTemplateFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutTemplate to fetch.
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutTemplates to fetch.
     */
    orderBy?:
        | Prisma.WorkoutTemplateOrderByWithRelationInput
        | Prisma.WorkoutTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for WorkoutTemplates.
     */
    cursor?: Prisma.WorkoutTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutTemplates.
     */
    distinct?:
        | Prisma.WorkoutTemplateScalarFieldEnum
        | Prisma.WorkoutTemplateScalarFieldEnum[];
};

/**
 * WorkoutTemplate findFirstOrThrow
 */
export type WorkoutTemplateFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutTemplate to fetch.
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutTemplates to fetch.
     */
    orderBy?:
        | Prisma.WorkoutTemplateOrderByWithRelationInput
        | Prisma.WorkoutTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for WorkoutTemplates.
     */
    cursor?: Prisma.WorkoutTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutTemplates.
     */
    distinct?:
        | Prisma.WorkoutTemplateScalarFieldEnum
        | Prisma.WorkoutTemplateScalarFieldEnum[];
};

/**
 * WorkoutTemplate findMany
 */
export type WorkoutTemplateFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutTemplates to fetch.
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutTemplates to fetch.
     */
    orderBy?:
        | Prisma.WorkoutTemplateOrderByWithRelationInput
        | Prisma.WorkoutTemplateOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing WorkoutTemplates.
     */
    cursor?: Prisma.WorkoutTemplateWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutTemplates from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutTemplates.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutTemplates.
     */
    distinct?:
        | Prisma.WorkoutTemplateScalarFieldEnum
        | Prisma.WorkoutTemplateScalarFieldEnum[];
};

/**
 * WorkoutTemplate create
 */
export type WorkoutTemplateCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * The data needed to create a WorkoutTemplate.
     */
    data: Prisma.XOR<
        Prisma.WorkoutTemplateCreateInput,
        Prisma.WorkoutTemplateUncheckedCreateInput
    >;
};

/**
 * WorkoutTemplate createMany
 */
export type WorkoutTemplateCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many WorkoutTemplates.
     */
    data:
        | Prisma.WorkoutTemplateCreateManyInput
        | Prisma.WorkoutTemplateCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * WorkoutTemplate createManyAndReturn
 */
export type WorkoutTemplateCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * The data used to create many WorkoutTemplates.
     */
    data:
        | Prisma.WorkoutTemplateCreateManyInput
        | Prisma.WorkoutTemplateCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * WorkoutTemplate update
 */
export type WorkoutTemplateUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * The data needed to update a WorkoutTemplate.
     */
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateInput,
        Prisma.WorkoutTemplateUncheckedUpdateInput
    >;
    /**
     * Choose, which WorkoutTemplate to update.
     */
    where: Prisma.WorkoutTemplateWhereUniqueInput;
};

/**
 * WorkoutTemplate updateMany
 */
export type WorkoutTemplateUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update WorkoutTemplates.
     */
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateManyMutationInput,
        Prisma.WorkoutTemplateUncheckedUpdateManyInput
    >;
    /**
     * Filter which WorkoutTemplates to update
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * Limit how many WorkoutTemplates to update.
     */
    limit?: number;
};

/**
 * WorkoutTemplate updateManyAndReturn
 */
export type WorkoutTemplateUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * The data used to update WorkoutTemplates.
     */
    data: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateManyMutationInput,
        Prisma.WorkoutTemplateUncheckedUpdateManyInput
    >;
    /**
     * Filter which WorkoutTemplates to update
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * Limit how many WorkoutTemplates to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * WorkoutTemplate upsert
 */
export type WorkoutTemplateUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * The filter to search for the WorkoutTemplate to update in case it exists.
     */
    where: Prisma.WorkoutTemplateWhereUniqueInput;
    /**
     * In case the WorkoutTemplate found by the `where` argument doesn't exist, create a new WorkoutTemplate with this data.
     */
    create: Prisma.XOR<
        Prisma.WorkoutTemplateCreateInput,
        Prisma.WorkoutTemplateUncheckedCreateInput
    >;
    /**
     * In case the WorkoutTemplate was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.WorkoutTemplateUpdateInput,
        Prisma.WorkoutTemplateUncheckedUpdateInput
    >;
};

/**
 * WorkoutTemplate delete
 */
export type WorkoutTemplateDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
    /**
     * Filter which WorkoutTemplate to delete.
     */
    where: Prisma.WorkoutTemplateWhereUniqueInput;
};

/**
 * WorkoutTemplate deleteMany
 */
export type WorkoutTemplateDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which WorkoutTemplates to delete
     */
    where?: Prisma.WorkoutTemplateWhereInput;
    /**
     * Limit how many WorkoutTemplates to delete.
     */
    limit?: number;
};

/**
 * WorkoutTemplate.user
 */
export type WorkoutTemplate$userArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the User
     */
    select?: Prisma.UserSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the User
     */
    omit?: Prisma.UserOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.UserInclude<ExtArgs> | null;
    where?: Prisma.UserWhereInput;
};

/**
 * WorkoutTemplate.exercises
 */
export type WorkoutTemplate$exercisesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplateExercise
     */
    select?: Prisma.WorkoutTemplateExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplateExercise
     */
    omit?: Prisma.WorkoutTemplateExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateExerciseInclude<ExtArgs> | null;
    where?: Prisma.WorkoutTemplateExerciseWhereInput;
    orderBy?:
        | Prisma.WorkoutTemplateExerciseOrderByWithRelationInput
        | Prisma.WorkoutTemplateExerciseOrderByWithRelationInput[];
    cursor?: Prisma.WorkoutTemplateExerciseWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?:
        | Prisma.WorkoutTemplateExerciseScalarFieldEnum
        | Prisma.WorkoutTemplateExerciseScalarFieldEnum[];
};

/**
 * WorkoutTemplate.sessions
 */
export type WorkoutTemplate$sessionsArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSession
     */
    select?: Prisma.WorkoutSessionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSession
     */
    omit?: Prisma.WorkoutSessionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionInclude<ExtArgs> | null;
    where?: Prisma.WorkoutSessionWhereInput;
    orderBy?:
        | Prisma.WorkoutSessionOrderByWithRelationInput
        | Prisma.WorkoutSessionOrderByWithRelationInput[];
    cursor?: Prisma.WorkoutSessionWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?:
        | Prisma.WorkoutSessionScalarFieldEnum
        | Prisma.WorkoutSessionScalarFieldEnum[];
};

/**
 * WorkoutTemplate.routines
 */
export type WorkoutTemplate$routinesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the RoutineTemplate
     */
    select?: Prisma.RoutineTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the RoutineTemplate
     */
    omit?: Prisma.RoutineTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.RoutineTemplateInclude<ExtArgs> | null;
    where?: Prisma.RoutineTemplateWhereInput;
    orderBy?:
        | Prisma.RoutineTemplateOrderByWithRelationInput
        | Prisma.RoutineTemplateOrderByWithRelationInput[];
    cursor?: Prisma.RoutineTemplateWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?:
        | Prisma.RoutineTemplateScalarFieldEnum
        | Prisma.RoutineTemplateScalarFieldEnum[];
};

/**
 * WorkoutTemplate without action
 */
export type WorkoutTemplateDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutTemplate
     */
    select?: Prisma.WorkoutTemplateSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutTemplate
     */
    omit?: Prisma.WorkoutTemplateOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutTemplateInclude<ExtArgs> | null;
};
