/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WorkoutSessionExercise` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model WorkoutSessionExercise
 *
 */
export type WorkoutSessionExerciseModel =
    runtime.Types.Result.DefaultSelection<Prisma.$WorkoutSessionExercisePayload>;

export type AggregateWorkoutSessionExercise = {
    _count: WorkoutSessionExerciseCountAggregateOutputType | null;
    _avg: WorkoutSessionExerciseAvgAggregateOutputType | null;
    _sum: WorkoutSessionExerciseSumAggregateOutputType | null;
    _min: WorkoutSessionExerciseMinAggregateOutputType | null;
    _max: WorkoutSessionExerciseMaxAggregateOutputType | null;
};

export type WorkoutSessionExerciseAvgAggregateOutputType = {
    orderIndex: number | null;
};

export type WorkoutSessionExerciseSumAggregateOutputType = {
    orderIndex: number | null;
};

export type WorkoutSessionExerciseMinAggregateOutputType = {
    id: string | null;
    sessionId: string | null;
    exerciseId: string | null;
    exerciseName: string | null;
    orderIndex: number | null;
};

export type WorkoutSessionExerciseMaxAggregateOutputType = {
    id: string | null;
    sessionId: string | null;
    exerciseId: string | null;
    exerciseName: string | null;
    orderIndex: number | null;
};

export type WorkoutSessionExerciseCountAggregateOutputType = {
    id: number;
    sessionId: number;
    exerciseId: number;
    exerciseName: number;
    orderIndex: number;
    _all: number;
};

export type WorkoutSessionExerciseAvgAggregateInputType = {
    orderIndex?: true;
};

export type WorkoutSessionExerciseSumAggregateInputType = {
    orderIndex?: true;
};

export type WorkoutSessionExerciseMinAggregateInputType = {
    id?: true;
    sessionId?: true;
    exerciseId?: true;
    exerciseName?: true;
    orderIndex?: true;
};

export type WorkoutSessionExerciseMaxAggregateInputType = {
    id?: true;
    sessionId?: true;
    exerciseId?: true;
    exerciseName?: true;
    orderIndex?: true;
};

export type WorkoutSessionExerciseCountAggregateInputType = {
    id?: true;
    sessionId?: true;
    exerciseId?: true;
    exerciseName?: true;
    orderIndex?: true;
    _all?: true;
};

export type WorkoutSessionExerciseAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which WorkoutSessionExercise to aggregate.
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessionExercises to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessionExercises from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessionExercises.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned WorkoutSessionExercises
     **/
    _count?: true | WorkoutSessionExerciseCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: WorkoutSessionExerciseAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: WorkoutSessionExerciseSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: WorkoutSessionExerciseMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: WorkoutSessionExerciseMaxAggregateInputType;
};

export type GetWorkoutSessionExerciseAggregateType<
    T extends WorkoutSessionExerciseAggregateArgs,
> = {
    [P in keyof T & keyof AggregateWorkoutSessionExercise]: P extends
        | '_count'
        | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateWorkoutSessionExercise[P]>
        : Prisma.GetScalarType<T[P], AggregateWorkoutSessionExercise[P]>;
};

export type WorkoutSessionExerciseGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    orderBy?:
        | Prisma.WorkoutSessionExerciseOrderByWithAggregationInput
        | Prisma.WorkoutSessionExerciseOrderByWithAggregationInput[];
    by:
        | Prisma.WorkoutSessionExerciseScalarFieldEnum[]
        | Prisma.WorkoutSessionExerciseScalarFieldEnum;
    having?: Prisma.WorkoutSessionExerciseScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: WorkoutSessionExerciseCountAggregateInputType | true;
    _avg?: WorkoutSessionExerciseAvgAggregateInputType;
    _sum?: WorkoutSessionExerciseSumAggregateInputType;
    _min?: WorkoutSessionExerciseMinAggregateInputType;
    _max?: WorkoutSessionExerciseMaxAggregateInputType;
};

export type WorkoutSessionExerciseGroupByOutputType = {
    id: string;
    sessionId: string;
    exerciseId: string;
    exerciseName: string;
    orderIndex: number;
    _count: WorkoutSessionExerciseCountAggregateOutputType | null;
    _avg: WorkoutSessionExerciseAvgAggregateOutputType | null;
    _sum: WorkoutSessionExerciseSumAggregateOutputType | null;
    _min: WorkoutSessionExerciseMinAggregateOutputType | null;
    _max: WorkoutSessionExerciseMaxAggregateOutputType | null;
};

export type GetWorkoutSessionExerciseGroupByPayload<
    T extends WorkoutSessionExerciseGroupByArgs,
> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<
            WorkoutSessionExerciseGroupByOutputType,
            T['by']
        > & {
            [P in keyof T &
                keyof WorkoutSessionExerciseGroupByOutputType]: P extends '_count'
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<
                          T[P],
                          WorkoutSessionExerciseGroupByOutputType[P]
                      >
                : Prisma.GetScalarType<
                      T[P],
                      WorkoutSessionExerciseGroupByOutputType[P]
                  >;
        }
    >
>;

export type WorkoutSessionExerciseWhereInput = {
    AND?:
        | Prisma.WorkoutSessionExerciseWhereInput
        | Prisma.WorkoutSessionExerciseWhereInput[];
    OR?: Prisma.WorkoutSessionExerciseWhereInput[];
    NOT?:
        | Prisma.WorkoutSessionExerciseWhereInput
        | Prisma.WorkoutSessionExerciseWhereInput[];
    id?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    sessionId?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    exerciseId?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    exerciseName?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    orderIndex?: Prisma.IntFilter<'WorkoutSessionExercise'> | number;
    session?: Prisma.XOR<
        Prisma.WorkoutSessionScalarRelationFilter,
        Prisma.WorkoutSessionWhereInput
    >;
    exercise?: Prisma.XOR<
        Prisma.ExerciseScalarRelationFilter,
        Prisma.ExerciseWhereInput
    >;
    sets?: Prisma.SetListRelationFilter;
};

export type WorkoutSessionExerciseOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    sessionId?: Prisma.SortOrder;
    exerciseId?: Prisma.SortOrder;
    exerciseName?: Prisma.SortOrder;
    orderIndex?: Prisma.SortOrder;
    session?: Prisma.WorkoutSessionOrderByWithRelationInput;
    exercise?: Prisma.ExerciseOrderByWithRelationInput;
    sets?: Prisma.SetOrderByRelationAggregateInput;
};

export type WorkoutSessionExerciseWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?:
            | Prisma.WorkoutSessionExerciseWhereInput
            | Prisma.WorkoutSessionExerciseWhereInput[];
        OR?: Prisma.WorkoutSessionExerciseWhereInput[];
        NOT?:
            | Prisma.WorkoutSessionExerciseWhereInput
            | Prisma.WorkoutSessionExerciseWhereInput[];
        sessionId?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
        exerciseId?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
        exerciseName?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
        orderIndex?: Prisma.IntFilter<'WorkoutSessionExercise'> | number;
        session?: Prisma.XOR<
            Prisma.WorkoutSessionScalarRelationFilter,
            Prisma.WorkoutSessionWhereInput
        >;
        exercise?: Prisma.XOR<
            Prisma.ExerciseScalarRelationFilter,
            Prisma.ExerciseWhereInput
        >;
        sets?: Prisma.SetListRelationFilter;
    },
    'id'
>;

export type WorkoutSessionExerciseOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    sessionId?: Prisma.SortOrder;
    exerciseId?: Prisma.SortOrder;
    exerciseName?: Prisma.SortOrder;
    orderIndex?: Prisma.SortOrder;
    _count?: Prisma.WorkoutSessionExerciseCountOrderByAggregateInput;
    _avg?: Prisma.WorkoutSessionExerciseAvgOrderByAggregateInput;
    _max?: Prisma.WorkoutSessionExerciseMaxOrderByAggregateInput;
    _min?: Prisma.WorkoutSessionExerciseMinOrderByAggregateInput;
    _sum?: Prisma.WorkoutSessionExerciseSumOrderByAggregateInput;
};

export type WorkoutSessionExerciseScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.WorkoutSessionExerciseScalarWhereWithAggregatesInput
        | Prisma.WorkoutSessionExerciseScalarWhereWithAggregatesInput[];
    OR?: Prisma.WorkoutSessionExerciseScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.WorkoutSessionExerciseScalarWhereWithAggregatesInput
        | Prisma.WorkoutSessionExerciseScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<'WorkoutSessionExercise'> | string;
    sessionId?:
        | Prisma.StringWithAggregatesFilter<'WorkoutSessionExercise'>
        | string;
    exerciseId?:
        | Prisma.StringWithAggregatesFilter<'WorkoutSessionExercise'>
        | string;
    exerciseName?:
        | Prisma.StringWithAggregatesFilter<'WorkoutSessionExercise'>
        | string;
    orderIndex?:
        | Prisma.IntWithAggregatesFilter<'WorkoutSessionExercise'>
        | number;
};

export type WorkoutSessionExerciseCreateInput = {
    id?: string;
    exerciseName: string;
    orderIndex: number;
    session: Prisma.WorkoutSessionCreateNestedOneWithoutExercisesInput;
    exercise: Prisma.ExerciseCreateNestedOneWithoutSessionExercisesInput;
    sets?: Prisma.SetCreateNestedManyWithoutWorkoutSessionExerciseInput;
};

export type WorkoutSessionExerciseUncheckedCreateInput = {
    id?: string;
    sessionId: string;
    exerciseId: string;
    exerciseName: string;
    orderIndex: number;
    sets?: Prisma.SetUncheckedCreateNestedManyWithoutWorkoutSessionExerciseInput;
};

export type WorkoutSessionExerciseUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    session?: Prisma.WorkoutSessionUpdateOneRequiredWithoutExercisesNestedInput;
    exercise?: Prisma.ExerciseUpdateOneRequiredWithoutSessionExercisesNestedInput;
    sets?: Prisma.SetUpdateManyWithoutWorkoutSessionExerciseNestedInput;
};

export type WorkoutSessionExerciseUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    sessionId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    sets?: Prisma.SetUncheckedUpdateManyWithoutWorkoutSessionExerciseNestedInput;
};

export type WorkoutSessionExerciseCreateManyInput = {
    id?: string;
    sessionId: string;
    exerciseId: string;
    exerciseName: string;
    orderIndex: number;
};

export type WorkoutSessionExerciseUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type WorkoutSessionExerciseUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    sessionId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type WorkoutSessionExerciseListRelationFilter = {
    every?: Prisma.WorkoutSessionExerciseWhereInput;
    some?: Prisma.WorkoutSessionExerciseWhereInput;
    none?: Prisma.WorkoutSessionExerciseWhereInput;
};

export type WorkoutSessionExerciseOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type WorkoutSessionExerciseCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    sessionId?: Prisma.SortOrder;
    exerciseId?: Prisma.SortOrder;
    exerciseName?: Prisma.SortOrder;
    orderIndex?: Prisma.SortOrder;
};

export type WorkoutSessionExerciseAvgOrderByAggregateInput = {
    orderIndex?: Prisma.SortOrder;
};

export type WorkoutSessionExerciseMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    sessionId?: Prisma.SortOrder;
    exerciseId?: Prisma.SortOrder;
    exerciseName?: Prisma.SortOrder;
    orderIndex?: Prisma.SortOrder;
};

export type WorkoutSessionExerciseMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    sessionId?: Prisma.SortOrder;
    exerciseId?: Prisma.SortOrder;
    exerciseName?: Prisma.SortOrder;
    orderIndex?: Prisma.SortOrder;
};

export type WorkoutSessionExerciseSumOrderByAggregateInput = {
    orderIndex?: Prisma.SortOrder;
};

export type WorkoutSessionExerciseScalarRelationFilter = {
    is?: Prisma.WorkoutSessionExerciseWhereInput;
    isNot?: Prisma.WorkoutSessionExerciseWhereInput;
};

export type WorkoutSessionExerciseCreateNestedManyWithoutExerciseInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput,
              Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput
          >
        | Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput[]
        | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput[];
    createMany?: Prisma.WorkoutSessionExerciseCreateManyExerciseInputEnvelope;
    connect?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
};

export type WorkoutSessionExerciseUncheckedCreateNestedManyWithoutExerciseInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput,
                  Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput
              >
            | Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput[]
            | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput[];
        connectOrCreate?:
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput[];
        createMany?: Prisma.WorkoutSessionExerciseCreateManyExerciseInputEnvelope;
        connect?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    };

export type WorkoutSessionExerciseUpdateManyWithoutExerciseNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput,
              Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput
          >
        | Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput[]
        | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput[];
    upsert?:
        | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutExerciseInput
        | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutExerciseInput[];
    createMany?: Prisma.WorkoutSessionExerciseCreateManyExerciseInputEnvelope;
    set?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    update?:
        | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutExerciseInput
        | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutExerciseInput[];
    updateMany?:
        | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutExerciseInput
        | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutExerciseInput[];
    deleteMany?:
        | Prisma.WorkoutSessionExerciseScalarWhereInput
        | Prisma.WorkoutSessionExerciseScalarWhereInput[];
};

export type WorkoutSessionExerciseUncheckedUpdateManyWithoutExerciseNestedInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput,
                  Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput
              >
            | Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput[]
            | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput[];
        connectOrCreate?:
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput[];
        upsert?:
            | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutExerciseInput
            | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutExerciseInput[];
        createMany?: Prisma.WorkoutSessionExerciseCreateManyExerciseInputEnvelope;
        set?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        disconnect?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        delete?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        connect?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        update?:
            | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutExerciseInput
            | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutExerciseInput[];
        updateMany?:
            | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutExerciseInput
            | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutExerciseInput[];
        deleteMany?:
            | Prisma.WorkoutSessionExerciseScalarWhereInput
            | Prisma.WorkoutSessionExerciseScalarWhereInput[];
    };

export type WorkoutSessionExerciseCreateNestedManyWithoutSessionInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionExerciseCreateWithoutSessionInput,
              Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput
          >
        | Prisma.WorkoutSessionExerciseCreateWithoutSessionInput[]
        | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput[];
    createMany?: Prisma.WorkoutSessionExerciseCreateManySessionInputEnvelope;
    connect?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
};

export type WorkoutSessionExerciseUncheckedCreateNestedManyWithoutSessionInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.WorkoutSessionExerciseCreateWithoutSessionInput,
                  Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput
              >
            | Prisma.WorkoutSessionExerciseCreateWithoutSessionInput[]
            | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput[];
        connectOrCreate?:
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput[];
        createMany?: Prisma.WorkoutSessionExerciseCreateManySessionInputEnvelope;
        connect?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    };

export type WorkoutSessionExerciseUpdateManyWithoutSessionNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.WorkoutSessionExerciseCreateWithoutSessionInput,
              Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput
          >
        | Prisma.WorkoutSessionExerciseCreateWithoutSessionInput[]
        | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput[];
    connectOrCreate?:
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput
        | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput[];
    upsert?:
        | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutSessionInput
        | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutSessionInput[];
    createMany?: Prisma.WorkoutSessionExerciseCreateManySessionInputEnvelope;
    set?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    disconnect?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    delete?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    connect?:
        | Prisma.WorkoutSessionExerciseWhereUniqueInput
        | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
    update?:
        | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutSessionInput
        | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutSessionInput[];
    updateMany?:
        | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutSessionInput
        | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutSessionInput[];
    deleteMany?:
        | Prisma.WorkoutSessionExerciseScalarWhereInput
        | Prisma.WorkoutSessionExerciseScalarWhereInput[];
};

export type WorkoutSessionExerciseUncheckedUpdateManyWithoutSessionNestedInput =
    {
        create?:
            | Prisma.XOR<
                  Prisma.WorkoutSessionExerciseCreateWithoutSessionInput,
                  Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput
              >
            | Prisma.WorkoutSessionExerciseCreateWithoutSessionInput[]
            | Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput[];
        connectOrCreate?:
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput
            | Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSessionInput[];
        upsert?:
            | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutSessionInput
            | Prisma.WorkoutSessionExerciseUpsertWithWhereUniqueWithoutSessionInput[];
        createMany?: Prisma.WorkoutSessionExerciseCreateManySessionInputEnvelope;
        set?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        disconnect?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        delete?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        connect?:
            | Prisma.WorkoutSessionExerciseWhereUniqueInput
            | Prisma.WorkoutSessionExerciseWhereUniqueInput[];
        update?:
            | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutSessionInput
            | Prisma.WorkoutSessionExerciseUpdateWithWhereUniqueWithoutSessionInput[];
        updateMany?:
            | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutSessionInput
            | Prisma.WorkoutSessionExerciseUpdateManyWithWhereWithoutSessionInput[];
        deleteMany?:
            | Prisma.WorkoutSessionExerciseScalarWhereInput
            | Prisma.WorkoutSessionExerciseScalarWhereInput[];
    };

export type WorkoutSessionExerciseCreateNestedOneWithoutSetsInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutSetsInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSetsInput
    >;
    connectOrCreate?: Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSetsInput;
    connect?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
};

export type WorkoutSessionExerciseUpdateOneRequiredWithoutSetsNestedInput = {
    create?: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutSetsInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSetsInput
    >;
    connectOrCreate?: Prisma.WorkoutSessionExerciseCreateOrConnectWithoutSetsInput;
    upsert?: Prisma.WorkoutSessionExerciseUpsertWithoutSetsInput;
    connect?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.WorkoutSessionExerciseUpdateToOneWithWhereWithoutSetsInput,
            Prisma.WorkoutSessionExerciseUpdateWithoutSetsInput
        >,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutSetsInput
    >;
};

export type WorkoutSessionExerciseCreateWithoutExerciseInput = {
    id?: string;
    exerciseName: string;
    orderIndex: number;
    session: Prisma.WorkoutSessionCreateNestedOneWithoutExercisesInput;
    sets?: Prisma.SetCreateNestedManyWithoutWorkoutSessionExerciseInput;
};

export type WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput = {
    id?: string;
    sessionId: string;
    exerciseName: string;
    orderIndex: number;
    sets?: Prisma.SetUncheckedCreateNestedManyWithoutWorkoutSessionExerciseInput;
};

export type WorkoutSessionExerciseCreateOrConnectWithoutExerciseInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput
    >;
};

export type WorkoutSessionExerciseCreateManyExerciseInputEnvelope = {
    data:
        | Prisma.WorkoutSessionExerciseCreateManyExerciseInput
        | Prisma.WorkoutSessionExerciseCreateManyExerciseInput[];
    skipDuplicates?: boolean;
};

export type WorkoutSessionExerciseUpsertWithWhereUniqueWithoutExerciseInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateWithoutExerciseInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutExerciseInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutExerciseInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutExerciseInput
    >;
};

export type WorkoutSessionExerciseUpdateWithWhereUniqueWithoutExerciseInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateWithoutExerciseInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutExerciseInput
    >;
};

export type WorkoutSessionExerciseUpdateManyWithWhereWithoutExerciseInput = {
    where: Prisma.WorkoutSessionExerciseScalarWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateManyMutationInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateManyWithoutExerciseInput
    >;
};

export type WorkoutSessionExerciseScalarWhereInput = {
    AND?:
        | Prisma.WorkoutSessionExerciseScalarWhereInput
        | Prisma.WorkoutSessionExerciseScalarWhereInput[];
    OR?: Prisma.WorkoutSessionExerciseScalarWhereInput[];
    NOT?:
        | Prisma.WorkoutSessionExerciseScalarWhereInput
        | Prisma.WorkoutSessionExerciseScalarWhereInput[];
    id?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    sessionId?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    exerciseId?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    exerciseName?: Prisma.StringFilter<'WorkoutSessionExercise'> | string;
    orderIndex?: Prisma.IntFilter<'WorkoutSessionExercise'> | number;
};

export type WorkoutSessionExerciseCreateWithoutSessionInput = {
    id?: string;
    exerciseName: string;
    orderIndex: number;
    exercise: Prisma.ExerciseCreateNestedOneWithoutSessionExercisesInput;
    sets?: Prisma.SetCreateNestedManyWithoutWorkoutSessionExerciseInput;
};

export type WorkoutSessionExerciseUncheckedCreateWithoutSessionInput = {
    id?: string;
    exerciseId: string;
    exerciseName: string;
    orderIndex: number;
    sets?: Prisma.SetUncheckedCreateNestedManyWithoutWorkoutSessionExerciseInput;
};

export type WorkoutSessionExerciseCreateOrConnectWithoutSessionInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutSessionInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput
    >;
};

export type WorkoutSessionExerciseCreateManySessionInputEnvelope = {
    data:
        | Prisma.WorkoutSessionExerciseCreateManySessionInput
        | Prisma.WorkoutSessionExerciseCreateManySessionInput[];
    skipDuplicates?: boolean;
};

export type WorkoutSessionExerciseUpsertWithWhereUniqueWithoutSessionInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateWithoutSessionInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutSessionInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutSessionInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSessionInput
    >;
};

export type WorkoutSessionExerciseUpdateWithWhereUniqueWithoutSessionInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateWithoutSessionInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutSessionInput
    >;
};

export type WorkoutSessionExerciseUpdateManyWithWhereWithoutSessionInput = {
    where: Prisma.WorkoutSessionExerciseScalarWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateManyMutationInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateManyWithoutSessionInput
    >;
};

export type WorkoutSessionExerciseCreateWithoutSetsInput = {
    id?: string;
    exerciseName: string;
    orderIndex: number;
    session: Prisma.WorkoutSessionCreateNestedOneWithoutExercisesInput;
    exercise: Prisma.ExerciseCreateNestedOneWithoutSessionExercisesInput;
};

export type WorkoutSessionExerciseUncheckedCreateWithoutSetsInput = {
    id?: string;
    sessionId: string;
    exerciseId: string;
    exerciseName: string;
    orderIndex: number;
};

export type WorkoutSessionExerciseCreateOrConnectWithoutSetsInput = {
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutSetsInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSetsInput
    >;
};

export type WorkoutSessionExerciseUpsertWithoutSetsInput = {
    update: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateWithoutSetsInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutSetsInput
    >;
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateWithoutSetsInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateWithoutSetsInput
    >;
    where?: Prisma.WorkoutSessionExerciseWhereInput;
};

export type WorkoutSessionExerciseUpdateToOneWithWhereWithoutSetsInput = {
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateWithoutSetsInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateWithoutSetsInput
    >;
};

export type WorkoutSessionExerciseUpdateWithoutSetsInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    session?: Prisma.WorkoutSessionUpdateOneRequiredWithoutExercisesNestedInput;
    exercise?: Prisma.ExerciseUpdateOneRequiredWithoutSessionExercisesNestedInput;
};

export type WorkoutSessionExerciseUncheckedUpdateWithoutSetsInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    sessionId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type WorkoutSessionExerciseCreateManyExerciseInput = {
    id?: string;
    sessionId: string;
    exerciseName: string;
    orderIndex: number;
};

export type WorkoutSessionExerciseUpdateWithoutExerciseInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    session?: Prisma.WorkoutSessionUpdateOneRequiredWithoutExercisesNestedInput;
    sets?: Prisma.SetUpdateManyWithoutWorkoutSessionExerciseNestedInput;
};

export type WorkoutSessionExerciseUncheckedUpdateWithoutExerciseInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    sessionId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    sets?: Prisma.SetUncheckedUpdateManyWithoutWorkoutSessionExerciseNestedInput;
};

export type WorkoutSessionExerciseUncheckedUpdateManyWithoutExerciseInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    sessionId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type WorkoutSessionExerciseCreateManySessionInput = {
    id?: string;
    exerciseId: string;
    exerciseName: string;
    orderIndex: number;
};

export type WorkoutSessionExerciseUpdateWithoutSessionInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    exercise?: Prisma.ExerciseUpdateOneRequiredWithoutSessionExercisesNestedInput;
    sets?: Prisma.SetUpdateManyWithoutWorkoutSessionExerciseNestedInput;
};

export type WorkoutSessionExerciseUncheckedUpdateWithoutSessionInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
    sets?: Prisma.SetUncheckedUpdateManyWithoutWorkoutSessionExerciseNestedInput;
};

export type WorkoutSessionExerciseUncheckedUpdateManyWithoutSessionInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseId?: Prisma.StringFieldUpdateOperationsInput | string;
    exerciseName?: Prisma.StringFieldUpdateOperationsInput | string;
    orderIndex?: Prisma.IntFieldUpdateOperationsInput | number;
};

/**
 * Count Type WorkoutSessionExerciseCountOutputType
 */

export type WorkoutSessionExerciseCountOutputType = {
    sets: number;
};

export type WorkoutSessionExerciseCountOutputTypeSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    sets?: boolean | WorkoutSessionExerciseCountOutputTypeCountSetsArgs;
};

/**
 * WorkoutSessionExerciseCountOutputType without action
 */
export type WorkoutSessionExerciseCountOutputTypeDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExerciseCountOutputType
     */
    select?: Prisma.WorkoutSessionExerciseCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * WorkoutSessionExerciseCountOutputType without action
 */
export type WorkoutSessionExerciseCountOutputTypeCountSetsArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.SetWhereInput;
};

export type WorkoutSessionExerciseSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        sessionId?: boolean;
        exerciseId?: boolean;
        exerciseName?: boolean;
        orderIndex?: boolean;
        session?: boolean | Prisma.WorkoutSessionDefaultArgs<ExtArgs>;
        exercise?: boolean | Prisma.ExerciseDefaultArgs<ExtArgs>;
        sets?: boolean | Prisma.WorkoutSessionExercise$setsArgs<ExtArgs>;
        _count?:
            | boolean
            | Prisma.WorkoutSessionExerciseCountOutputTypeDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutSessionExercise']
>;

export type WorkoutSessionExerciseSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        sessionId?: boolean;
        exerciseId?: boolean;
        exerciseName?: boolean;
        orderIndex?: boolean;
        session?: boolean | Prisma.WorkoutSessionDefaultArgs<ExtArgs>;
        exercise?: boolean | Prisma.ExerciseDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutSessionExercise']
>;

export type WorkoutSessionExerciseSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        sessionId?: boolean;
        exerciseId?: boolean;
        exerciseName?: boolean;
        orderIndex?: boolean;
        session?: boolean | Prisma.WorkoutSessionDefaultArgs<ExtArgs>;
        exercise?: boolean | Prisma.ExerciseDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['workoutSessionExercise']
>;

export type WorkoutSessionExerciseSelectScalar = {
    id?: boolean;
    sessionId?: boolean;
    exerciseId?: boolean;
    exerciseName?: boolean;
    orderIndex?: boolean;
};

export type WorkoutSessionExerciseOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    'id' | 'sessionId' | 'exerciseId' | 'exerciseName' | 'orderIndex',
    ExtArgs['result']['workoutSessionExercise']
>;
export type WorkoutSessionExerciseInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    session?: boolean | Prisma.WorkoutSessionDefaultArgs<ExtArgs>;
    exercise?: boolean | Prisma.ExerciseDefaultArgs<ExtArgs>;
    sets?: boolean | Prisma.WorkoutSessionExercise$setsArgs<ExtArgs>;
    _count?:
        | boolean
        | Prisma.WorkoutSessionExerciseCountOutputTypeDefaultArgs<ExtArgs>;
};
export type WorkoutSessionExerciseIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    session?: boolean | Prisma.WorkoutSessionDefaultArgs<ExtArgs>;
    exercise?: boolean | Prisma.ExerciseDefaultArgs<ExtArgs>;
};
export type WorkoutSessionExerciseIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    session?: boolean | Prisma.WorkoutSessionDefaultArgs<ExtArgs>;
    exercise?: boolean | Prisma.ExerciseDefaultArgs<ExtArgs>;
};

export type $WorkoutSessionExercisePayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: 'WorkoutSessionExercise';
    objects: {
        session: Prisma.$WorkoutSessionPayload<ExtArgs>;
        exercise: Prisma.$ExercisePayload<ExtArgs>;
        sets: Prisma.$SetPayload<ExtArgs>[];
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            sessionId: string;
            exerciseId: string;
            exerciseName: string;
            orderIndex: number;
        },
        ExtArgs['result']['workoutSessionExercise']
    >;
    composites: {};
};

export type WorkoutSessionExerciseGetPayload<
    S extends boolean | null | undefined | WorkoutSessionExerciseDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WorkoutSessionExercisePayload, S>;

export type WorkoutSessionExerciseCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<
    WorkoutSessionExerciseFindManyArgs,
    'select' | 'include' | 'distinct' | 'omit'
> & {
    select?: WorkoutSessionExerciseCountAggregateInputType | true;
};

export interface WorkoutSessionExerciseDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>['model']['WorkoutSessionExercise'];
        meta: { name: 'WorkoutSessionExercise' };
    };
    /**
     * Find zero or one WorkoutSessionExercise that matches the filter.
     * @param {WorkoutSessionExerciseFindUniqueArgs} args - Arguments to find a WorkoutSessionExercise
     * @example
     * // Get one WorkoutSessionExercise
     * const workoutSessionExercise = await prisma.workoutSessionExercise.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends WorkoutSessionExerciseFindUniqueArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseFindUniqueArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'findUnique',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one WorkoutSessionExercise that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {WorkoutSessionExerciseFindUniqueOrThrowArgs} args - Arguments to find a WorkoutSessionExercise
     * @example
     * // Get one WorkoutSessionExercise
     * const workoutSessionExercise = await prisma.workoutSessionExercise.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends WorkoutSessionExerciseFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseFindUniqueOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first WorkoutSessionExercise that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseFindFirstArgs} args - Arguments to find a WorkoutSessionExercise
     * @example
     * // Get one WorkoutSessionExercise
     * const workoutSessionExercise = await prisma.workoutSessionExercise.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends WorkoutSessionExerciseFindFirstArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseFindFirstArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'findFirst',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first WorkoutSessionExercise that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseFindFirstOrThrowArgs} args - Arguments to find a WorkoutSessionExercise
     * @example
     * // Get one WorkoutSessionExercise
     * const workoutSessionExercise = await prisma.workoutSessionExercise.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends WorkoutSessionExerciseFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseFindFirstOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'findFirstOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more WorkoutSessionExercises that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all WorkoutSessionExercises
     * const workoutSessionExercises = await prisma.workoutSessionExercise.findMany()
     *
     * // Get first 10 WorkoutSessionExercises
     * const workoutSessionExercises = await prisma.workoutSessionExercise.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const workoutSessionExerciseWithIdOnly = await prisma.workoutSessionExercise.findMany({ select: { id: true } })
     *
     */
    findMany<T extends WorkoutSessionExerciseFindManyArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseFindManyArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'findMany',
            GlobalOmitOptions
        >
    >;

    /**
     * Create a WorkoutSessionExercise.
     * @param {WorkoutSessionExerciseCreateArgs} args - Arguments to create a WorkoutSessionExercise.
     * @example
     * // Create one WorkoutSessionExercise
     * const WorkoutSessionExercise = await prisma.workoutSessionExercise.create({
     *   data: {
     *     // ... data to create a WorkoutSessionExercise
     *   }
     * })
     *
     */
    create<T extends WorkoutSessionExerciseCreateArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionExerciseCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'create',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many WorkoutSessionExercises.
     * @param {WorkoutSessionExerciseCreateManyArgs} args - Arguments to create many WorkoutSessionExercises.
     * @example
     * // Create many WorkoutSessionExercises
     * const workoutSessionExercise = await prisma.workoutSessionExercise.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends WorkoutSessionExerciseCreateManyArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseCreateManyArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many WorkoutSessionExercises and returns the data saved in the database.
     * @param {WorkoutSessionExerciseCreateManyAndReturnArgs} args - Arguments to create many WorkoutSessionExercises.
     * @example
     * // Create many WorkoutSessionExercises
     * const workoutSessionExercise = await prisma.workoutSessionExercise.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many WorkoutSessionExercises and only return the `id`
     * const workoutSessionExerciseWithIdOnly = await prisma.workoutSessionExercise.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<
        T extends WorkoutSessionExerciseCreateManyAndReturnArgs,
    >(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseCreateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'createManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a WorkoutSessionExercise.
     * @param {WorkoutSessionExerciseDeleteArgs} args - Arguments to delete one WorkoutSessionExercise.
     * @example
     * // Delete one WorkoutSessionExercise
     * const WorkoutSessionExercise = await prisma.workoutSessionExercise.delete({
     *   where: {
     *     // ... filter to delete one WorkoutSessionExercise
     *   }
     * })
     *
     */
    delete<T extends WorkoutSessionExerciseDeleteArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionExerciseDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'delete',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one WorkoutSessionExercise.
     * @param {WorkoutSessionExerciseUpdateArgs} args - Arguments to update one WorkoutSessionExercise.
     * @example
     * // Update one WorkoutSessionExercise
     * const workoutSessionExercise = await prisma.workoutSessionExercise.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends WorkoutSessionExerciseUpdateArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionExerciseUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'update',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more WorkoutSessionExercises.
     * @param {WorkoutSessionExerciseDeleteManyArgs} args - Arguments to filter WorkoutSessionExercises to delete.
     * @example
     * // Delete a few WorkoutSessionExercises
     * const { count } = await prisma.workoutSessionExercise.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends WorkoutSessionExerciseDeleteManyArgs>(
        args?: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseDeleteManyArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more WorkoutSessionExercises.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many WorkoutSessionExercises
     * const workoutSessionExercise = await prisma.workoutSessionExercise.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends WorkoutSessionExerciseUpdateManyArgs>(
        args: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseUpdateManyArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more WorkoutSessionExercises and returns the data updated in the database.
     * @param {WorkoutSessionExerciseUpdateManyAndReturnArgs} args - Arguments to update many WorkoutSessionExercises.
     * @example
     * // Update many WorkoutSessionExercises
     * const workoutSessionExercise = await prisma.workoutSessionExercise.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more WorkoutSessionExercises and only return the `id`
     * const workoutSessionExerciseWithIdOnly = await prisma.workoutSessionExercise.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<
        T extends WorkoutSessionExerciseUpdateManyAndReturnArgs,
    >(
        args: Prisma.SelectSubset<
            T,
            WorkoutSessionExerciseUpdateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'updateManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one WorkoutSessionExercise.
     * @param {WorkoutSessionExerciseUpsertArgs} args - Arguments to update or create a WorkoutSessionExercise.
     * @example
     * // Update or create a WorkoutSessionExercise
     * const workoutSessionExercise = await prisma.workoutSessionExercise.upsert({
     *   create: {
     *     // ... data to create a WorkoutSessionExercise
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the WorkoutSessionExercise we want to update
     *   }
     * })
     */
    upsert<T extends WorkoutSessionExerciseUpsertArgs>(
        args: Prisma.SelectSubset<T, WorkoutSessionExerciseUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionExerciseClient<
        runtime.Types.Result.GetResult<
            Prisma.$WorkoutSessionExercisePayload<ExtArgs>,
            T,
            'upsert',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of WorkoutSessionExercises.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseCountArgs} args - Arguments to filter WorkoutSessionExercises to count.
     * @example
     * // Count the number of WorkoutSessionExercises
     * const count = await prisma.workoutSessionExercise.count({
     *   where: {
     *     // ... the filter for the WorkoutSessionExercises we want to count
     *   }
     * })
     **/
    count<T extends WorkoutSessionExerciseCountArgs>(
        args?: Prisma.Subset<T, WorkoutSessionExerciseCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<
                      T['select'],
                      WorkoutSessionExerciseCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a WorkoutSessionExercise.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends WorkoutSessionExerciseAggregateArgs>(
        args: Prisma.Subset<T, WorkoutSessionExerciseAggregateArgs>,
    ): Prisma.PrismaPromise<GetWorkoutSessionExerciseAggregateType<T>>;

    /**
     * Group by WorkoutSessionExercise.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {WorkoutSessionExerciseGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends WorkoutSessionExerciseGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: WorkoutSessionExerciseGroupByArgs['orderBy'] }
            : { orderBy?: WorkoutSessionExerciseGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                'Field ',
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : 'take' extends Prisma.Keys<T>
                ? 'orderBy' extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : 'skip' extends Prisma.Keys<T>
                  ? 'orderBy' extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<
            T,
            WorkoutSessionExerciseGroupByArgs,
            OrderByArg
        > &
            InputErrors,
    ): {} extends InputErrors
        ? GetWorkoutSessionExerciseGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the WorkoutSessionExercise model
     */
    readonly fields: WorkoutSessionExerciseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkoutSessionExercise.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkoutSessionExerciseClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: 'PrismaPromise';
    session<T extends Prisma.WorkoutSessionDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.WorkoutSessionDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__WorkoutSessionClient<
        | runtime.Types.Result.GetResult<
              Prisma.$WorkoutSessionPayload<ExtArgs>,
              T,
              'findUniqueOrThrow',
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    exercise<T extends Prisma.ExerciseDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.ExerciseDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__ExerciseClient<
        | runtime.Types.Result.GetResult<
              Prisma.$ExercisePayload<ExtArgs>,
              T,
              'findUniqueOrThrow',
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    sets<T extends Prisma.WorkoutSessionExercise$setsArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<
            T,
            Prisma.WorkoutSessionExercise$setsArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$SetPayload<ExtArgs>,
              T,
              'findMany',
              GlobalOmitOptions
          >
        | Null
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the WorkoutSessionExercise model
 */
export interface WorkoutSessionExerciseFieldRefs {
    readonly id: Prisma.FieldRef<'WorkoutSessionExercise', 'String'>;
    readonly sessionId: Prisma.FieldRef<'WorkoutSessionExercise', 'String'>;
    readonly exerciseId: Prisma.FieldRef<'WorkoutSessionExercise', 'String'>;
    readonly exerciseName: Prisma.FieldRef<'WorkoutSessionExercise', 'String'>;
    readonly orderIndex: Prisma.FieldRef<'WorkoutSessionExercise', 'Int'>;
}

// Custom InputTypes
/**
 * WorkoutSessionExercise findUnique
 */
export type WorkoutSessionExerciseFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSessionExercise to fetch.
     */
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
};

/**
 * WorkoutSessionExercise findUniqueOrThrow
 */
export type WorkoutSessionExerciseFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSessionExercise to fetch.
     */
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
};

/**
 * WorkoutSessionExercise findFirst
 */
export type WorkoutSessionExerciseFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSessionExercise to fetch.
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessionExercises to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for WorkoutSessionExercises.
     */
    cursor?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessionExercises from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessionExercises.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutSessionExercises.
     */
    distinct?:
        | Prisma.WorkoutSessionExerciseScalarFieldEnum
        | Prisma.WorkoutSessionExerciseScalarFieldEnum[];
};

/**
 * WorkoutSessionExercise findFirstOrThrow
 */
export type WorkoutSessionExerciseFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSessionExercise to fetch.
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessionExercises to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for WorkoutSessionExercises.
     */
    cursor?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessionExercises from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessionExercises.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutSessionExercises.
     */
    distinct?:
        | Prisma.WorkoutSessionExerciseScalarFieldEnum
        | Prisma.WorkoutSessionExerciseScalarFieldEnum[];
};

/**
 * WorkoutSessionExercise findMany
 */
export type WorkoutSessionExerciseFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * Filter, which WorkoutSessionExercises to fetch.
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of WorkoutSessionExercises to fetch.
     */
    orderBy?:
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput
        | Prisma.WorkoutSessionExerciseOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing WorkoutSessionExercises.
     */
    cursor?: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` WorkoutSessionExercises from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` WorkoutSessionExercises.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of WorkoutSessionExercises.
     */
    distinct?:
        | Prisma.WorkoutSessionExerciseScalarFieldEnum
        | Prisma.WorkoutSessionExerciseScalarFieldEnum[];
};

/**
 * WorkoutSessionExercise create
 */
export type WorkoutSessionExerciseCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * The data needed to create a WorkoutSessionExercise.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateInput
    >;
};

/**
 * WorkoutSessionExercise createMany
 */
export type WorkoutSessionExerciseCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many WorkoutSessionExercises.
     */
    data:
        | Prisma.WorkoutSessionExerciseCreateManyInput
        | Prisma.WorkoutSessionExerciseCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * WorkoutSessionExercise createManyAndReturn
 */
export type WorkoutSessionExerciseCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * The data used to create many WorkoutSessionExercises.
     */
    data:
        | Prisma.WorkoutSessionExerciseCreateManyInput
        | Prisma.WorkoutSessionExerciseCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * WorkoutSessionExercise update
 */
export type WorkoutSessionExerciseUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * The data needed to update a WorkoutSessionExercise.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateInput
    >;
    /**
     * Choose, which WorkoutSessionExercise to update.
     */
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
};

/**
 * WorkoutSessionExercise updateMany
 */
export type WorkoutSessionExerciseUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update WorkoutSessionExercises.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateManyMutationInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateManyInput
    >;
    /**
     * Filter which WorkoutSessionExercises to update
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * Limit how many WorkoutSessionExercises to update.
     */
    limit?: number;
};

/**
 * WorkoutSessionExercise updateManyAndReturn
 */
export type WorkoutSessionExerciseUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * The data used to update WorkoutSessionExercises.
     */
    data: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateManyMutationInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateManyInput
    >;
    /**
     * Filter which WorkoutSessionExercises to update
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * Limit how many WorkoutSessionExercises to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * WorkoutSessionExercise upsert
 */
export type WorkoutSessionExerciseUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * The filter to search for the WorkoutSessionExercise to update in case it exists.
     */
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
    /**
     * In case the WorkoutSessionExercise found by the `where` argument doesn't exist, create a new WorkoutSessionExercise with this data.
     */
    create: Prisma.XOR<
        Prisma.WorkoutSessionExerciseCreateInput,
        Prisma.WorkoutSessionExerciseUncheckedCreateInput
    >;
    /**
     * In case the WorkoutSessionExercise was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.WorkoutSessionExerciseUpdateInput,
        Prisma.WorkoutSessionExerciseUncheckedUpdateInput
    >;
};

/**
 * WorkoutSessionExercise delete
 */
export type WorkoutSessionExerciseDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
    /**
     * Filter which WorkoutSessionExercise to delete.
     */
    where: Prisma.WorkoutSessionExerciseWhereUniqueInput;
};

/**
 * WorkoutSessionExercise deleteMany
 */
export type WorkoutSessionExerciseDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which WorkoutSessionExercises to delete
     */
    where?: Prisma.WorkoutSessionExerciseWhereInput;
    /**
     * Limit how many WorkoutSessionExercises to delete.
     */
    limit?: number;
};

/**
 * WorkoutSessionExercise.sets
 */
export type WorkoutSessionExercise$setsArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Set
     */
    select?: Prisma.SetSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Set
     */
    omit?: Prisma.SetOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SetInclude<ExtArgs> | null;
    where?: Prisma.SetWhereInput;
    orderBy?:
        | Prisma.SetOrderByWithRelationInput
        | Prisma.SetOrderByWithRelationInput[];
    cursor?: Prisma.SetWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?: Prisma.SetScalarFieldEnum | Prisma.SetScalarFieldEnum[];
};

/**
 * WorkoutSessionExercise without action
 */
export type WorkoutSessionExerciseDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the WorkoutSessionExercise
     */
    select?: Prisma.WorkoutSessionExerciseSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the WorkoutSessionExercise
     */
    omit?: Prisma.WorkoutSessionExerciseOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.WorkoutSessionExerciseInclude<ExtArgs> | null;
};
