/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser';

export type * from '../models.js';
export type * from './prismaNamespace.js';

export const Decimal = runtime.Decimal;

export const NullTypes = {
    DbNull: runtime.NullTypes.DbNull as new (
        secret: never,
    ) => typeof runtime.DbNull,
    JsonNull: runtime.NullTypes.JsonNull as new (
        secret: never,
    ) => typeof runtime.JsonNull,
    AnyNull: runtime.NullTypes.AnyNull as new (
        secret: never,
    ) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

export const ModelName = {
    User: 'User',
    Exercise: 'Exercise',
    WorkoutTemplate: 'WorkoutTemplate',
    WorkoutTemplateExercise: 'WorkoutTemplateExercise',
    WorkoutSession: 'WorkoutSession',
    WorkoutSessionExercise: 'WorkoutSessionExercise',
    Set: 'Set',
    Routine: 'Routine',
    RoutineTemplate: 'RoutineTemplate',
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
    ReadUncommitted: 'ReadUncommitted',
    ReadCommitted: 'ReadCommitted',
    RepeatableRead: 'RepeatableRead',
    Serializable: 'Serializable',
} as const);

export type TransactionIsolationLevel =
    (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const UserScalarFieldEnum = {
    id: 'id',
    email: 'email',
    passwordHash: 'passwordHash',
    createdAt: 'createdAt',
} as const;

export type UserScalarFieldEnum =
    (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

export const ExerciseScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    name: 'name',
    description: 'description',
} as const;

export type ExerciseScalarFieldEnum =
    (typeof ExerciseScalarFieldEnum)[keyof typeof ExerciseScalarFieldEnum];

export const WorkoutTemplateScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    name: 'name',
    description: 'description',
} as const;

export type WorkoutTemplateScalarFieldEnum =
    (typeof WorkoutTemplateScalarFieldEnum)[keyof typeof WorkoutTemplateScalarFieldEnum];

export const WorkoutTemplateExerciseScalarFieldEnum = {
    id: 'id',
    workoutTemplateId: 'workoutTemplateId',
    exerciseId: 'exerciseId',
    orderIndex: 'orderIndex',
    targetSets: 'targetSets',
    targetRepsMin: 'targetRepsMin',
    targetRepsMax: 'targetRepsMax',
    restSeconds: 'restSeconds',
    supersetGroupId: 'supersetGroupId',
} as const;

export type WorkoutTemplateExerciseScalarFieldEnum =
    (typeof WorkoutTemplateExerciseScalarFieldEnum)[keyof typeof WorkoutTemplateExerciseScalarFieldEnum];

export const WorkoutSessionScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    workoutTemplateId: 'workoutTemplateId',
    startedAt: 'startedAt',
    finishedAt: 'finishedAt',
} as const;

export type WorkoutSessionScalarFieldEnum =
    (typeof WorkoutSessionScalarFieldEnum)[keyof typeof WorkoutSessionScalarFieldEnum];

export const WorkoutSessionExerciseScalarFieldEnum = {
    id: 'id',
    sessionId: 'sessionId',
    exerciseId: 'exerciseId',
    exerciseName: 'exerciseName',
    orderIndex: 'orderIndex',
} as const;

export type WorkoutSessionExerciseScalarFieldEnum =
    (typeof WorkoutSessionExerciseScalarFieldEnum)[keyof typeof WorkoutSessionExerciseScalarFieldEnum];

export const SetScalarFieldEnum = {
    id: 'id',
    workoutSessionExerciseId: 'workoutSessionExerciseId',
    setIndex: 'setIndex',
    metrics: 'metrics',
    completedAt: 'completedAt',
} as const;

export type SetScalarFieldEnum =
    (typeof SetScalarFieldEnum)[keyof typeof SetScalarFieldEnum];

export const RoutineScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    name: 'name',
    description: 'description',
} as const;

export type RoutineScalarFieldEnum =
    (typeof RoutineScalarFieldEnum)[keyof typeof RoutineScalarFieldEnum];

export const RoutineTemplateScalarFieldEnum = {
    id: 'id',
    routineId: 'routineId',
    workoutTemplateId: 'workoutTemplateId',
    dayOfWeek: 'dayOfWeek',
} as const;

export type RoutineTemplateScalarFieldEnum =
    (typeof RoutineTemplateScalarFieldEnum)[keyof typeof RoutineTemplateScalarFieldEnum];

export const SortOrder = {
    asc: 'asc',
    desc: 'desc',
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const JsonNullValueInput = {
    JsonNull: JsonNull,
} as const;

export type JsonNullValueInput =
    (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput];

export const QueryMode = {
    default: 'default',
    insensitive: 'insensitive',
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
    first: 'first',
    last: 'last',
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];

export const JsonNullValueFilter = {
    DbNull: DbNull,
    JsonNull: JsonNull,
    AnyNull: AnyNull,
} as const;

export type JsonNullValueFilter =
    (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter];
