/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/client';
import type * as Prisma from '../models.js';
import { type PrismaClient } from './class.js';

export type * from '../models.js';

export type DMMF = typeof runtime.DMMF;

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>;

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError =
    runtime.PrismaClientKnownRequestError;
export type PrismaClientKnownRequestError =
    runtime.PrismaClientKnownRequestError;

export const PrismaClientUnknownRequestError =
    runtime.PrismaClientUnknownRequestError;
export type PrismaClientUnknownRequestError =
    runtime.PrismaClientUnknownRequestError;

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;

export const PrismaClientInitializationError =
    runtime.PrismaClientInitializationError;
export type PrismaClientInitializationError =
    runtime.PrismaClientInitializationError;

export const PrismaClientValidationError = runtime.PrismaClientValidationError;
export type PrismaClientValidationError = runtime.PrismaClientValidationError;

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag;
export const empty = runtime.empty;
export const join = runtime.join;
export const raw = runtime.raw;
export const Sql = runtime.Sql;
export type Sql = runtime.Sql;

/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal;
export type Decimal = runtime.Decimal;

export type DecimalJsLike = runtime.DecimalJsLike;

/**
 * Extensions
 */
export type Extension = runtime.Types.Extensions.UserArgs;
export const getExtensionContext = runtime.Extensions.getExtensionContext;
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<
    T,
    F
>;
export type Payload<
    T,
    F extends runtime.Operation = never,
> = runtime.Types.Public.Payload<T, F>;
export type Result<
    T,
    A,
    F extends runtime.Operation,
> = runtime.Types.Public.Result<T, A, F>;
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>;

export type PrismaVersion = {
    client: string;
    engine: string;
};

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
    client: '7.8.0',
    engine: '3c6e192761c0362d496ed980de936e2f3cebcd3a',
};

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes;
export type JsonObject = runtime.JsonObject;
export type JsonArray = runtime.JsonArray;
export type JsonValue = runtime.JsonValue;
export type InputJsonObject = runtime.InputJsonObject;
export type InputJsonArray = runtime.InputJsonArray;
export type InputJsonValue = runtime.InputJsonValue;

export const NullTypes = {
    DbNull: runtime.NullTypes.DbNull as new (
        secret: never,
    ) => typeof runtime.DbNull,
    JsonNull: runtime.NullTypes.JsonNull as new (
        secret: never,
    ) => typeof runtime.JsonNull,
    AnyNull: runtime.NullTypes.AnyNull as new (
        secret: never,
    ) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

type SelectAndInclude = {
    select: any;
    include: any;
};

type SelectAndOmit = {
    select: any;
    omit: any;
};

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
    [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
    [key in keyof T]: key extends keyof U ? T[key] : never;
} & (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {});

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
    [key in keyof T]: key extends keyof U ? T[key] : never;
} & K;

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> = T extends object
    ? U extends object
        ? (Without<T, U> & U) | (Without<U, T> & T)
        : U
    : T;

/**
 * Is T a Record?
 */
type IsObject<T extends any> =
    T extends Array<any>
        ? False
        : T extends Date
          ? False
          : T extends Uint8Array
            ? False
            : T extends BigInt
              ? False
              : T extends object
                ? True
                : False;

/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T;

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
    {
        // Merge all but K
        [P in K]: Prisma__Pick<O, P & keyof O>; // With K possibilities
    }[K];

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>;

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>;

type _Either<O extends object, K extends Key, strict extends Boolean> = {
    1: EitherStrict<O, K>;
    0: EitherLoose<O, K>;
}[strict];

export type Either<
    O extends object,
    K extends Key,
    strict extends Boolean = 1,
> = O extends unknown ? _Either<O, K, strict> : never;

export type Union = any;

export type PatchUndefined<O extends object, O1 extends object> = {
    [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K];
} & {};

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
    U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
    ? I
    : never;

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<
    Overwrite<
        U,
        {
            [K in keyof U]-?: At<U, K>;
        }
    >
>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown
    ? AtStrict<O, K>
    : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function
    ? A
    : {
          [K in keyof A]: A[K];
      } & {};

export type OptionalFlat<O> = {
    [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
    [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
    O extends unknown
        ?
              | (K extends keyof O ? { [P in K]: O[P] } & O : O)
              | ({ [P in keyof O as P extends K ? P : never]-?: O[P] } & O)
        : never
>;

type _Strict<U, _U = U> = U extends unknown
    ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>>
    : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False;

export type True = 1;

export type False = 0;

export type Not<B extends Boolean> = {
    0: 1;
    1: 0;
}[B];

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
    ? 0 // anything `never` is false
    : A1 extends A2
      ? 1
      : 0;

export type Has<U extends Union, U1 extends Union> = Not<
    Extends<Exclude<U1, U>, U1>
>;

export type Or<B1 extends Boolean, B2 extends Boolean> = {
    0: {
        0: 0;
        1: 1;
    };
    1: {
        0: 1;
        1: 1;
    };
}[B1][B2];

export type Keys<U extends Union> = U extends unknown ? keyof U : never;

export type GetScalarType<T, O> = O extends object
    ? {
          [P in keyof T]: P extends keyof O ? O[P] : never;
      }
    : never;

type FieldPaths<T, U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>> =
    IsObject<T> extends True ? U : T;

export type GetHavingFields<T> = {
    [K in keyof T]: Or<
        Or<Extends<'OR', K>, Extends<'AND', K>>,
        Extends<'NOT', K>
    > extends True
        ? // infer is only needed to not hit TS limit
          // based on the brilliant idea of Pierre-Antoine Mills
          // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
          T[K] extends infer TK
            ? GetHavingFields<
                  UnEnumerate<TK> extends object
                      ? Merge<UnEnumerate<TK>>
                      : never
              >
            : never
        : {} extends FieldPaths<T[K]>
          ? never
          : K;
}[keyof T];

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never;
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>;
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T;

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<
    T,
    K extends Enumerable<keyof T> | keyof T,
> = Prisma__Pick<T, MaybeTupleToUnion<K>>;

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}`
    ? never
    : T;

export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>;

type FieldRefInputType<Model, FieldType> = Model extends never
    ? never
    : FieldRef<Model, FieldType>;

export const ModelName = {
    User: 'User',
    Exercise: 'Exercise',
    WorkoutTemplate: 'WorkoutTemplate',
    WorkoutTemplateExercise: 'WorkoutTemplateExercise',
    WorkoutSession: 'WorkoutSession',
    WorkoutSessionExercise: 'WorkoutSessionExercise',
    Set: 'Set',
    Routine: 'Routine',
    RoutineTemplate: 'RoutineTemplate',
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils
    .Fn<
    { extArgs: runtime.Types.Extensions.InternalArgs },
    runtime.Types.Utils.Record<string, any>
> {
    returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>;
}

export type TypeMap<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> = {
    globalOmitOptions: {
        omit: GlobalOmitOptions;
    };
    meta: {
        modelProps:
            | 'user'
            | 'exercise'
            | 'workoutTemplate'
            | 'workoutTemplateExercise'
            | 'workoutSession'
            | 'workoutSessionExercise'
            | 'set'
            | 'routine'
            | 'routineTemplate';
        txIsolationLevel: TransactionIsolationLevel;
    };
    model: {
        User: {
            payload: Prisma.$UserPayload<ExtArgs>;
            fields: Prisma.UserFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.UserFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>;
                };
                findFirst: {
                    args: Prisma.UserFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>;
                };
                findMany: {
                    args: Prisma.UserFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[];
                };
                create: {
                    args: Prisma.UserCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>;
                };
                createMany: {
                    args: Prisma.UserCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[];
                };
                delete: {
                    args: Prisma.UserDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>;
                };
                update: {
                    args: Prisma.UserUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>;
                };
                deleteMany: {
                    args: Prisma.UserDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.UserUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[];
                };
                upsert: {
                    args: Prisma.UserUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>;
                };
                aggregate: {
                    args: Prisma.UserAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateUser>;
                };
                groupBy: {
                    args: Prisma.UserGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[];
                };
                count: {
                    args: Prisma.UserCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType>
                        | number;
                };
            };
        };
        Exercise: {
            payload: Prisma.$ExercisePayload<ExtArgs>;
            fields: Prisma.ExerciseFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.ExerciseFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.ExerciseFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>;
                };
                findFirst: {
                    args: Prisma.ExerciseFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.ExerciseFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>;
                };
                findMany: {
                    args: Prisma.ExerciseFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>[];
                };
                create: {
                    args: Prisma.ExerciseCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>;
                };
                createMany: {
                    args: Prisma.ExerciseCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.ExerciseCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>[];
                };
                delete: {
                    args: Prisma.ExerciseDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>;
                };
                update: {
                    args: Prisma.ExerciseUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>;
                };
                deleteMany: {
                    args: Prisma.ExerciseDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.ExerciseUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.ExerciseUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>[];
                };
                upsert: {
                    args: Prisma.ExerciseUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$ExercisePayload>;
                };
                aggregate: {
                    args: Prisma.ExerciseAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateExercise>;
                };
                groupBy: {
                    args: Prisma.ExerciseGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.ExerciseGroupByOutputType>[];
                };
                count: {
                    args: Prisma.ExerciseCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.ExerciseCountAggregateOutputType>
                        | number;
                };
            };
        };
        WorkoutTemplate: {
            payload: Prisma.$WorkoutTemplatePayload<ExtArgs>;
            fields: Prisma.WorkoutTemplateFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.WorkoutTemplateFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.WorkoutTemplateFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>;
                };
                findFirst: {
                    args: Prisma.WorkoutTemplateFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.WorkoutTemplateFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>;
                };
                findMany: {
                    args: Prisma.WorkoutTemplateFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>[];
                };
                create: {
                    args: Prisma.WorkoutTemplateCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>;
                };
                createMany: {
                    args: Prisma.WorkoutTemplateCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.WorkoutTemplateCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>[];
                };
                delete: {
                    args: Prisma.WorkoutTemplateDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>;
                };
                update: {
                    args: Prisma.WorkoutTemplateUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>;
                };
                deleteMany: {
                    args: Prisma.WorkoutTemplateDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.WorkoutTemplateUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.WorkoutTemplateUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>[];
                };
                upsert: {
                    args: Prisma.WorkoutTemplateUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplatePayload>;
                };
                aggregate: {
                    args: Prisma.WorkoutTemplateAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateWorkoutTemplate>;
                };
                groupBy: {
                    args: Prisma.WorkoutTemplateGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.WorkoutTemplateGroupByOutputType>[];
                };
                count: {
                    args: Prisma.WorkoutTemplateCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.WorkoutTemplateCountAggregateOutputType>
                        | number;
                };
            };
        };
        WorkoutTemplateExercise: {
            payload: Prisma.$WorkoutTemplateExercisePayload<ExtArgs>;
            fields: Prisma.WorkoutTemplateExerciseFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.WorkoutTemplateExerciseFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.WorkoutTemplateExerciseFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>;
                };
                findFirst: {
                    args: Prisma.WorkoutTemplateExerciseFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.WorkoutTemplateExerciseFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>;
                };
                findMany: {
                    args: Prisma.WorkoutTemplateExerciseFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>[];
                };
                create: {
                    args: Prisma.WorkoutTemplateExerciseCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>;
                };
                createMany: {
                    args: Prisma.WorkoutTemplateExerciseCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.WorkoutTemplateExerciseCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>[];
                };
                delete: {
                    args: Prisma.WorkoutTemplateExerciseDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>;
                };
                update: {
                    args: Prisma.WorkoutTemplateExerciseUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>;
                };
                deleteMany: {
                    args: Prisma.WorkoutTemplateExerciseDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.WorkoutTemplateExerciseUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.WorkoutTemplateExerciseUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>[];
                };
                upsert: {
                    args: Prisma.WorkoutTemplateExerciseUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutTemplateExercisePayload>;
                };
                aggregate: {
                    args: Prisma.WorkoutTemplateExerciseAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateWorkoutTemplateExercise>;
                };
                groupBy: {
                    args: Prisma.WorkoutTemplateExerciseGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.WorkoutTemplateExerciseGroupByOutputType>[];
                };
                count: {
                    args: Prisma.WorkoutTemplateExerciseCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.WorkoutTemplateExerciseCountAggregateOutputType>
                        | number;
                };
            };
        };
        WorkoutSession: {
            payload: Prisma.$WorkoutSessionPayload<ExtArgs>;
            fields: Prisma.WorkoutSessionFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.WorkoutSessionFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.WorkoutSessionFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>;
                };
                findFirst: {
                    args: Prisma.WorkoutSessionFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.WorkoutSessionFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>;
                };
                findMany: {
                    args: Prisma.WorkoutSessionFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>[];
                };
                create: {
                    args: Prisma.WorkoutSessionCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>;
                };
                createMany: {
                    args: Prisma.WorkoutSessionCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.WorkoutSessionCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>[];
                };
                delete: {
                    args: Prisma.WorkoutSessionDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>;
                };
                update: {
                    args: Prisma.WorkoutSessionUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>;
                };
                deleteMany: {
                    args: Prisma.WorkoutSessionDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.WorkoutSessionUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.WorkoutSessionUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>[];
                };
                upsert: {
                    args: Prisma.WorkoutSessionUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionPayload>;
                };
                aggregate: {
                    args: Prisma.WorkoutSessionAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateWorkoutSession>;
                };
                groupBy: {
                    args: Prisma.WorkoutSessionGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.WorkoutSessionGroupByOutputType>[];
                };
                count: {
                    args: Prisma.WorkoutSessionCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.WorkoutSessionCountAggregateOutputType>
                        | number;
                };
            };
        };
        WorkoutSessionExercise: {
            payload: Prisma.$WorkoutSessionExercisePayload<ExtArgs>;
            fields: Prisma.WorkoutSessionExerciseFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.WorkoutSessionExerciseFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.WorkoutSessionExerciseFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>;
                };
                findFirst: {
                    args: Prisma.WorkoutSessionExerciseFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.WorkoutSessionExerciseFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>;
                };
                findMany: {
                    args: Prisma.WorkoutSessionExerciseFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>[];
                };
                create: {
                    args: Prisma.WorkoutSessionExerciseCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>;
                };
                createMany: {
                    args: Prisma.WorkoutSessionExerciseCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.WorkoutSessionExerciseCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>[];
                };
                delete: {
                    args: Prisma.WorkoutSessionExerciseDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>;
                };
                update: {
                    args: Prisma.WorkoutSessionExerciseUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>;
                };
                deleteMany: {
                    args: Prisma.WorkoutSessionExerciseDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.WorkoutSessionExerciseUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.WorkoutSessionExerciseUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>[];
                };
                upsert: {
                    args: Prisma.WorkoutSessionExerciseUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$WorkoutSessionExercisePayload>;
                };
                aggregate: {
                    args: Prisma.WorkoutSessionExerciseAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateWorkoutSessionExercise>;
                };
                groupBy: {
                    args: Prisma.WorkoutSessionExerciseGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.WorkoutSessionExerciseGroupByOutputType>[];
                };
                count: {
                    args: Prisma.WorkoutSessionExerciseCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.WorkoutSessionExerciseCountAggregateOutputType>
                        | number;
                };
            };
        };
        Set: {
            payload: Prisma.$SetPayload<ExtArgs>;
            fields: Prisma.SetFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.SetFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.SetFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>;
                };
                findFirst: {
                    args: Prisma.SetFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.SetFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>;
                };
                findMany: {
                    args: Prisma.SetFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>[];
                };
                create: {
                    args: Prisma.SetCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>;
                };
                createMany: {
                    args: Prisma.SetCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.SetCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>[];
                };
                delete: {
                    args: Prisma.SetDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>;
                };
                update: {
                    args: Prisma.SetUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>;
                };
                deleteMany: {
                    args: Prisma.SetDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.SetUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.SetUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>[];
                };
                upsert: {
                    args: Prisma.SetUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$SetPayload>;
                };
                aggregate: {
                    args: Prisma.SetAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateSet>;
                };
                groupBy: {
                    args: Prisma.SetGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.SetGroupByOutputType>[];
                };
                count: {
                    args: Prisma.SetCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.SetCountAggregateOutputType>
                        | number;
                };
            };
        };
        Routine: {
            payload: Prisma.$RoutinePayload<ExtArgs>;
            fields: Prisma.RoutineFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.RoutineFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.RoutineFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>;
                };
                findFirst: {
                    args: Prisma.RoutineFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.RoutineFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>;
                };
                findMany: {
                    args: Prisma.RoutineFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>[];
                };
                create: {
                    args: Prisma.RoutineCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>;
                };
                createMany: {
                    args: Prisma.RoutineCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.RoutineCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>[];
                };
                delete: {
                    args: Prisma.RoutineDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>;
                };
                update: {
                    args: Prisma.RoutineUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>;
                };
                deleteMany: {
                    args: Prisma.RoutineDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.RoutineUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.RoutineUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>[];
                };
                upsert: {
                    args: Prisma.RoutineUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutinePayload>;
                };
                aggregate: {
                    args: Prisma.RoutineAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateRoutine>;
                };
                groupBy: {
                    args: Prisma.RoutineGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.RoutineGroupByOutputType>[];
                };
                count: {
                    args: Prisma.RoutineCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.RoutineCountAggregateOutputType>
                        | number;
                };
            };
        };
        RoutineTemplate: {
            payload: Prisma.$RoutineTemplatePayload<ExtArgs>;
            fields: Prisma.RoutineTemplateFieldRefs;
            operations: {
                findUnique: {
                    args: Prisma.RoutineTemplateFindUniqueArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload> | null;
                };
                findUniqueOrThrow: {
                    args: Prisma.RoutineTemplateFindUniqueOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>;
                };
                findFirst: {
                    args: Prisma.RoutineTemplateFindFirstArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload> | null;
                };
                findFirstOrThrow: {
                    args: Prisma.RoutineTemplateFindFirstOrThrowArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>;
                };
                findMany: {
                    args: Prisma.RoutineTemplateFindManyArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>[];
                };
                create: {
                    args: Prisma.RoutineTemplateCreateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>;
                };
                createMany: {
                    args: Prisma.RoutineTemplateCreateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                createManyAndReturn: {
                    args: Prisma.RoutineTemplateCreateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>[];
                };
                delete: {
                    args: Prisma.RoutineTemplateDeleteArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>;
                };
                update: {
                    args: Prisma.RoutineTemplateUpdateArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>;
                };
                deleteMany: {
                    args: Prisma.RoutineTemplateDeleteManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateMany: {
                    args: Prisma.RoutineTemplateUpdateManyArgs<ExtArgs>;
                    result: BatchPayload;
                };
                updateManyAndReturn: {
                    args: Prisma.RoutineTemplateUpdateManyAndReturnArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>[];
                };
                upsert: {
                    args: Prisma.RoutineTemplateUpsertArgs<ExtArgs>;
                    result: runtime.Types.Utils.PayloadToResult<Prisma.$RoutineTemplatePayload>;
                };
                aggregate: {
                    args: Prisma.RoutineTemplateAggregateArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.AggregateRoutineTemplate>;
                };
                groupBy: {
                    args: Prisma.RoutineTemplateGroupByArgs<ExtArgs>;
                    result: runtime.Types.Utils.Optional<Prisma.RoutineTemplateGroupByOutputType>[];
                };
                count: {
                    args: Prisma.RoutineTemplateCountArgs<ExtArgs>;
                    result:
                        | runtime.Types.Utils.Optional<Prisma.RoutineTemplateCountAggregateOutputType>
                        | number;
                };
            };
        };
    };
} & {
    other: {
        payload: any;
        operations: {
            $executeRaw: {
                args: [query: TemplateStringsArray | Sql, ...values: any[]];
                result: any;
            };
            $executeRawUnsafe: {
                args: [query: string, ...values: any[]];
                result: any;
            };
            $queryRaw: {
                args: [query: TemplateStringsArray | Sql, ...values: any[]];
                result: any;
            };
            $queryRawUnsafe: {
                args: [query: string, ...values: any[]];
                result: any;
            };
        };
    };
};

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
    ReadUncommitted: 'ReadUncommitted',
    ReadCommitted: 'ReadCommitted',
    RepeatableRead: 'RepeatableRead',
    Serializable: 'Serializable',
} as const);

export type TransactionIsolationLevel =
    (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const UserScalarFieldEnum = {
    id: 'id',
    email: 'email',
    passwordHash: 'passwordHash',
    createdAt: 'createdAt',
} as const;

export type UserScalarFieldEnum =
    (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

export const ExerciseScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    name: 'name',
    description: 'description',
} as const;

export type ExerciseScalarFieldEnum =
    (typeof ExerciseScalarFieldEnum)[keyof typeof ExerciseScalarFieldEnum];

export const WorkoutTemplateScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    name: 'name',
    description: 'description',
} as const;

export type WorkoutTemplateScalarFieldEnum =
    (typeof WorkoutTemplateScalarFieldEnum)[keyof typeof WorkoutTemplateScalarFieldEnum];

export const WorkoutTemplateExerciseScalarFieldEnum = {
    id: 'id',
    workoutTemplateId: 'workoutTemplateId',
    exerciseId: 'exerciseId',
    orderIndex: 'orderIndex',
    targetSets: 'targetSets',
    targetRepsMin: 'targetRepsMin',
    targetRepsMax: 'targetRepsMax',
    restSeconds: 'restSeconds',
    supersetGroupId: 'supersetGroupId',
} as const;

export type WorkoutTemplateExerciseScalarFieldEnum =
    (typeof WorkoutTemplateExerciseScalarFieldEnum)[keyof typeof WorkoutTemplateExerciseScalarFieldEnum];

export const WorkoutSessionScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    workoutTemplateId: 'workoutTemplateId',
    startedAt: 'startedAt',
    finishedAt: 'finishedAt',
} as const;

export type WorkoutSessionScalarFieldEnum =
    (typeof WorkoutSessionScalarFieldEnum)[keyof typeof WorkoutSessionScalarFieldEnum];

export const WorkoutSessionExerciseScalarFieldEnum = {
    id: 'id',
    sessionId: 'sessionId',
    exerciseId: 'exerciseId',
    exerciseName: 'exerciseName',
    orderIndex: 'orderIndex',
} as const;

export type WorkoutSessionExerciseScalarFieldEnum =
    (typeof WorkoutSessionExerciseScalarFieldEnum)[keyof typeof WorkoutSessionExerciseScalarFieldEnum];

export const SetScalarFieldEnum = {
    id: 'id',
    workoutSessionExerciseId: 'workoutSessionExerciseId',
    setIndex: 'setIndex',
    metrics: 'metrics',
    completedAt: 'completedAt',
} as const;

export type SetScalarFieldEnum =
    (typeof SetScalarFieldEnum)[keyof typeof SetScalarFieldEnum];

export const RoutineScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    name: 'name',
    description: 'description',
} as const;

export type RoutineScalarFieldEnum =
    (typeof RoutineScalarFieldEnum)[keyof typeof RoutineScalarFieldEnum];

export const RoutineTemplateScalarFieldEnum = {
    id: 'id',
    routineId: 'routineId',
    workoutTemplateId: 'workoutTemplateId',
    dayOfWeek: 'dayOfWeek',
} as const;

export type RoutineTemplateScalarFieldEnum =
    (typeof RoutineTemplateScalarFieldEnum)[keyof typeof RoutineTemplateScalarFieldEnum];

export const SortOrder = {
    asc: 'asc',
    desc: 'desc',
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const JsonNullValueInput = {
    JsonNull: JsonNull,
} as const;

export type JsonNullValueInput =
    (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput];

export const QueryMode = {
    default: 'default',
    insensitive: 'insensitive',
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
    first: 'first',
    last: 'last',
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];

export const JsonNullValueFilter = {
    DbNull: DbNull,
    JsonNull: JsonNull,
    AnyNull: AnyNull,
} as const;

export type JsonNullValueFilter =
    (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter];

/**
 * Field references
 */

/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'String'
>;

/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'String[]'
>;

/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'DateTime'
>;

/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'DateTime[]'
>;

/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'Int'
>;

/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'Int[]'
>;

/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'Json'
>;

/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'QueryMode'
>;

/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'Float'
>;

/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<
    $PrismaModel,
    'Float[]'
>;

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
    count: number;
};

export const defineExtension = runtime.Extensions
    .defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<
    'define',
    TypeMapCb,
    runtime.Types.Extensions.DefaultArgs
>;
export type DefaultPrismaClient = PrismaClient;
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal';
export type PrismaClientOptions = (
    | {
          /**
           * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
           */
          adapter: runtime.SqlDriverAdapterFactory;
          accelerateUrl?: never;
      }
    | {
          /**
           * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
           */
          accelerateUrl: string;
          adapter?: never;
      }
) & {
    /**
     * @default "colorless"
     */
    errorFormat?: ErrorFormat;
    /**
     * @example
     * ```
     * // Shorthand for `emit: 'stdout'`
     * log: ['query', 'info', 'warn', 'error']
     *
     * // Emit as events only
     * log: [
     *   { emit: 'event', level: 'query' },
     *   { emit: 'event', level: 'info' },
     *   { emit: 'event', level: 'warn' }
     *   { emit: 'event', level: 'error' }
     * ]
     *
     * / Emit as events and log to stdout
     * og: [
     *  { emit: 'stdout', level: 'query' },
     *  { emit: 'stdout', level: 'info' },
     *  { emit: 'stdout', level: 'warn' }
     *  { emit: 'stdout', level: 'error' }
     *
     * ```
     * Read more in our [docs](https://pris.ly/d/logging).
     */
    log?: (LogLevel | LogDefinition)[];
    /**
     * The default values for transactionOptions
     * maxWait ?= 2000
     * timeout ?= 5000
     */
    transactionOptions?: {
        maxWait?: number;
        timeout?: number;
        isolationLevel?: TransactionIsolationLevel;
    };
    /**
     * Global configuration for omitting model fields by default.
     *
     * @example
     * ```
     * const prisma = new PrismaClient({
     *   omit: {
     *     user: {
     *       password: true
     *     }
     *   }
     * })
     * ```
     */
    omit?: GlobalOmitConfig;
    /**
     * SQL commenter plugins that add metadata to SQL queries as comments.
     * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
     *
     * @example
     * ```
     * const prisma = new PrismaClient({
     *   adapter,
     *   comments: [
     *     traceContext(),
     *     queryInsights(),
     *   ],
     * })
     * ```
     */
    comments?: runtime.SqlCommenterPlugin[];
    /**
     * Optional maximum size for the query plan cache. If not provided, a default size will be used.
     * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
     * performance for applications that execute a large number of unique queries, while a smaller
     * cache size can reduce memory usage.
     *
     * @example
     * ```
     * const prisma = new PrismaClient({
     *   adapter,
     *   queryPlanCacheMaxSize: 100,
     * })
     * ```
     */
    queryPlanCacheMaxSize?: number;
};
export type GlobalOmitConfig = {
    user?: Prisma.UserOmit;
    exercise?: Prisma.ExerciseOmit;
    workoutTemplate?: Prisma.WorkoutTemplateOmit;
    workoutTemplateExercise?: Prisma.WorkoutTemplateExerciseOmit;
    workoutSession?: Prisma.WorkoutSessionOmit;
    workoutSessionExercise?: Prisma.WorkoutSessionExerciseOmit;
    set?: Prisma.SetOmit;
    routine?: Prisma.RoutineOmit;
    routineTemplate?: Prisma.RoutineTemplateOmit;
};

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error';
export type LogDefinition = {
    level: LogLevel;
    emit: 'stdout' | 'event';
};

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
    T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> =
    T extends Array<LogLevel | LogDefinition> ? GetLogType<T[number]> : never;

export type QueryEvent = {
    timestamp: Date;
    query: string;
    params: string;
    duration: number;
    target: string;
};

export type LogEvent = {
    timestamp: Date;
    message: string;
    target: string;
};
/* End Types for Logging */

export type PrismaAction =
    | 'findUnique'
    | 'findUniqueOrThrow'
    | 'findMany'
    | 'findFirst'
    | 'findFirstOrThrow'
    | 'create'
    | 'createMany'
    | 'createManyAndReturn'
    | 'update'
    | 'updateMany'
    | 'updateManyAndReturn'
    | 'upsert'
    | 'delete'
    | 'deleteMany'
    | 'executeRaw'
    | 'queryRaw'
    | 'aggregate'
    | 'count'
    | 'runCommandRaw'
    | 'findRaw'
    | 'groupBy';

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<
    DefaultPrismaClient,
    runtime.ITXClientDenyList
>;
